# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.4.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.4.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/beardj/GIT_RPO/RaftLib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/beardj/GIT_RPO/RaftLib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.4.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.4.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.4.0/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.4.0/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.4.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.4.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/beardj/GIT_RPO/RaftLib/CMakeFiles /Users/beardj/GIT_RPO/RaftLib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/beardj/GIT_RPO/RaftLib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named raft

# Build rule for target.
raft: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 raft
.PHONY : raft

# fast build rule for target.
raft/fast:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/build
.PHONY : raft/fast

affinity.o: affinity.cpp.o

.PHONY : affinity.o

# target to build an object file
affinity.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/affinity.cpp.o
.PHONY : affinity.cpp.o

affinity.i: affinity.cpp.i

.PHONY : affinity.i

# target to preprocess a source file
affinity.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/affinity.cpp.i
.PHONY : affinity.cpp.i

affinity.s: affinity.cpp.s

.PHONY : affinity.s

# target to generate assembly for a file
affinity.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/affinity.cpp.s
.PHONY : affinity.cpp.s

allocate.o: allocate.cpp.o

.PHONY : allocate.o

# target to build an object file
allocate.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/allocate.cpp.o
.PHONY : allocate.cpp.o

allocate.i: allocate.cpp.i

.PHONY : allocate.i

# target to preprocess a source file
allocate.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/allocate.cpp.i
.PHONY : allocate.cpp.i

allocate.s: allocate.cpp.s

.PHONY : allocate.s

# target to generate assembly for a file
allocate.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/allocate.cpp.s
.PHONY : allocate.cpp.s

basicparallel.o: basicparallel.cpp.o

.PHONY : basicparallel.o

# target to build an object file
basicparallel.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/basicparallel.cpp.o
.PHONY : basicparallel.cpp.o

basicparallel.i: basicparallel.cpp.i

.PHONY : basicparallel.i

# target to preprocess a source file
basicparallel.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/basicparallel.cpp.i
.PHONY : basicparallel.cpp.i

basicparallel.s: basicparallel.cpp.s

.PHONY : basicparallel.s

# target to generate assembly for a file
basicparallel.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/basicparallel.cpp.s
.PHONY : basicparallel.cpp.s

common.o: common.cpp.o

.PHONY : common.o

# target to build an object file
common.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/common.cpp.o
.PHONY : common.cpp.o

common.i: common.cpp.i

.PHONY : common.i

# target to preprocess a source file
common.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/common.cpp.i
.PHONY : common.cpp.i

common.s: common.cpp.s

.PHONY : common.s

# target to generate assembly for a file
common.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/common.cpp.s
.PHONY : common.cpp.s

dynalloc.o: dynalloc.cpp.o

.PHONY : dynalloc.o

# target to build an object file
dynalloc.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/dynalloc.cpp.o
.PHONY : dynalloc.cpp.o

dynalloc.i: dynalloc.cpp.i

.PHONY : dynalloc.i

# target to preprocess a source file
dynalloc.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/dynalloc.cpp.i
.PHONY : dynalloc.cpp.i

dynalloc.s: dynalloc.cpp.s

.PHONY : dynalloc.s

# target to generate assembly for a file
dynalloc.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/dynalloc.cpp.s
.PHONY : dynalloc.cpp.s

fifo/Clock.o: fifo/Clock.cpp.o

.PHONY : fifo/Clock.o

# target to build an object file
fifo/Clock.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/Clock.cpp.o
.PHONY : fifo/Clock.cpp.o

fifo/Clock.i: fifo/Clock.cpp.i

.PHONY : fifo/Clock.i

# target to preprocess a source file
fifo/Clock.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/Clock.cpp.i
.PHONY : fifo/Clock.cpp.i

fifo/Clock.s: fifo/Clock.cpp.s

.PHONY : fifo/Clock.s

# target to generate assembly for a file
fifo/Clock.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/Clock.cpp.s
.PHONY : fifo/Clock.cpp.s

fifo/clockimpl.o: fifo/clockimpl.cpp.o

.PHONY : fifo/clockimpl.o

# target to build an object file
fifo/clockimpl.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/clockimpl.cpp.o
.PHONY : fifo/clockimpl.cpp.o

fifo/clockimpl.i: fifo/clockimpl.cpp.i

.PHONY : fifo/clockimpl.i

# target to preprocess a source file
fifo/clockimpl.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/clockimpl.cpp.i
.PHONY : fifo/clockimpl.cpp.i

fifo/clockimpl.s: fifo/clockimpl.cpp.s

.PHONY : fifo/clockimpl.s

# target to generate assembly for a file
fifo/clockimpl.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/clockimpl.cpp.s
.PHONY : fifo/clockimpl.cpp.s

fifo/fifo.o: fifo/fifo.cpp.o

.PHONY : fifo/fifo.o

# target to build an object file
fifo/fifo.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/fifo.cpp.o
.PHONY : fifo/fifo.cpp.o

fifo/fifo.i: fifo/fifo.cpp.i

.PHONY : fifo/fifo.i

# target to preprocess a source file
fifo/fifo.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/fifo.cpp.i
.PHONY : fifo/fifo.cpp.i

fifo/fifo.s: fifo/fifo.cpp.s

.PHONY : fifo/fifo.s

# target to generate assembly for a file
fifo/fifo.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/fifo.cpp.s
.PHONY : fifo/fifo.cpp.s

fifo/getrandom.o: fifo/getrandom.c.o

.PHONY : fifo/getrandom.o

# target to build an object file
fifo/getrandom.c.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/getrandom.c.o
.PHONY : fifo/getrandom.c.o

fifo/getrandom.i: fifo/getrandom.c.i

.PHONY : fifo/getrandom.i

# target to preprocess a source file
fifo/getrandom.c.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/getrandom.c.i
.PHONY : fifo/getrandom.c.i

fifo/getrandom.s: fifo/getrandom.c.s

.PHONY : fifo/getrandom.s

# target to generate assembly for a file
fifo/getrandom.c.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/getrandom.c.s
.PHONY : fifo/getrandom.c.s

fifo/pointer.o: fifo/pointer.cpp.o

.PHONY : fifo/pointer.o

# target to build an object file
fifo/pointer.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/pointer.cpp.o
.PHONY : fifo/pointer.cpp.o

fifo/pointer.i: fifo/pointer.cpp.i

.PHONY : fifo/pointer.i

# target to preprocess a source file
fifo/pointer.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/pointer.cpp.i
.PHONY : fifo/pointer.cpp.i

fifo/pointer.s: fifo/pointer.cpp.s

.PHONY : fifo/pointer.s

# target to generate assembly for a file
fifo/pointer.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/pointer.cpp.s
.PHONY : fifo/pointer.cpp.s

fifo/procwait.o: fifo/procwait.cpp.o

.PHONY : fifo/procwait.o

# target to build an object file
fifo/procwait.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/procwait.cpp.o
.PHONY : fifo/procwait.cpp.o

fifo/procwait.i: fifo/procwait.cpp.i

.PHONY : fifo/procwait.i

# target to preprocess a source file
fifo/procwait.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/procwait.cpp.i
.PHONY : fifo/procwait.cpp.i

fifo/procwait.s: fifo/procwait.cpp.s

.PHONY : fifo/procwait.s

# target to generate assembly for a file
fifo/procwait.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/procwait.cpp.s
.PHONY : fifo/procwait.cpp.s

fifo/resolution.o: fifo/resolution.cpp.o

.PHONY : fifo/resolution.o

# target to build an object file
fifo/resolution.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/resolution.cpp.o
.PHONY : fifo/resolution.cpp.o

fifo/resolution.i: fifo/resolution.cpp.i

.PHONY : fifo/resolution.i

# target to preprocess a source file
fifo/resolution.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/resolution.cpp.i
.PHONY : fifo/resolution.cpp.i

fifo/resolution.s: fifo/resolution.cpp.s

.PHONY : fifo/resolution.s

# target to generate assembly for a file
fifo/resolution.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/resolution.cpp.s
.PHONY : fifo/resolution.cpp.s

fifo/shm.o: fifo/shm.cpp.o

.PHONY : fifo/shm.o

# target to build an object file
fifo/shm.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/shm.cpp.o
.PHONY : fifo/shm.cpp.o

fifo/shm.i: fifo/shm.cpp.i

.PHONY : fifo/shm.i

# target to preprocess a source file
fifo/shm.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/shm.cpp.i
.PHONY : fifo/shm.cpp.i

fifo/shm.s: fifo/shm.cpp.s

.PHONY : fifo/shm.s

# target to generate assembly for a file
fifo/shm.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/shm.cpp.s
.PHONY : fifo/shm.cpp.s

fifo/signal.o: fifo/signal.cpp.o

.PHONY : fifo/signal.o

# target to build an object file
fifo/signal.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/signal.cpp.o
.PHONY : fifo/signal.cpp.o

fifo/signal.i: fifo/signal.cpp.i

.PHONY : fifo/signal.i

# target to preprocess a source file
fifo/signal.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/signal.cpp.i
.PHONY : fifo/signal.cpp.i

fifo/signal.s: fifo/signal.cpp.s

.PHONY : fifo/signal.s

# target to generate assembly for a file
fifo/signal.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/signal.cpp.s
.PHONY : fifo/signal.cpp.s

fifo/signaldata.o: fifo/signaldata.cpp.o

.PHONY : fifo/signaldata.o

# target to build an object file
fifo/signaldata.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/signaldata.cpp.o
.PHONY : fifo/signaldata.cpp.o

fifo/signaldata.i: fifo/signaldata.cpp.i

.PHONY : fifo/signaldata.i

# target to preprocess a source file
fifo/signaldata.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/signaldata.cpp.i
.PHONY : fifo/signaldata.cpp.i

fifo/signaldata.s: fifo/signaldata.cpp.s

.PHONY : fifo/signaldata.s

# target to generate assembly for a file
fifo/signaldata.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/signaldata.cpp.s
.PHONY : fifo/signaldata.cpp.s

fifo/systeminfo.o: fifo/systeminfo.cpp.o

.PHONY : fifo/systeminfo.o

# target to build an object file
fifo/systeminfo.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/systeminfo.cpp.o
.PHONY : fifo/systeminfo.cpp.o

fifo/systeminfo.i: fifo/systeminfo.cpp.i

.PHONY : fifo/systeminfo.i

# target to preprocess a source file
fifo/systeminfo.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/systeminfo.cpp.i
.PHONY : fifo/systeminfo.cpp.i

fifo/systeminfo.s: fifo/systeminfo.cpp.s

.PHONY : fifo/systeminfo.s

# target to generate assembly for a file
fifo/systeminfo.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/fifo/systeminfo.cpp.s
.PHONY : fifo/systeminfo.cpp.s

globalmap.o: globalmap.cpp.o

.PHONY : globalmap.o

# target to build an object file
globalmap.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/globalmap.cpp.o
.PHONY : globalmap.cpp.o

globalmap.i: globalmap.cpp.i

.PHONY : globalmap.i

# target to preprocess a source file
globalmap.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/globalmap.cpp.i
.PHONY : globalmap.cpp.i

globalmap.s: globalmap.cpp.s

.PHONY : globalmap.s

# target to generate assembly for a file
globalmap.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/globalmap.cpp.s
.PHONY : globalmap.cpp.s

graphtools.o: graphtools.cpp.o

.PHONY : graphtools.o

# target to build an object file
graphtools.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/graphtools.cpp.o
.PHONY : graphtools.cpp.o

graphtools.i: graphtools.cpp.i

.PHONY : graphtools.i

# target to preprocess a source file
graphtools.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/graphtools.cpp.i
.PHONY : graphtools.cpp.i

graphtools.s: graphtools.cpp.s

.PHONY : graphtools.s

# target to generate assembly for a file
graphtools.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/graphtools.cpp.s
.PHONY : graphtools.cpp.s

kernel.o: kernel.cpp.o

.PHONY : kernel.o

# target to build an object file
kernel.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/kernel.cpp.o
.PHONY : kernel.cpp.o

kernel.i: kernel.cpp.i

.PHONY : kernel.i

# target to preprocess a source file
kernel.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/kernel.cpp.i
.PHONY : kernel.cpp.i

kernel.s: kernel.cpp.s

.PHONY : kernel.s

# target to generate assembly for a file
kernel.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/kernel.cpp.s
.PHONY : kernel.cpp.s

kernelcontainer.o: kernelcontainer.cpp.o

.PHONY : kernelcontainer.o

# target to build an object file
kernelcontainer.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/kernelcontainer.cpp.o
.PHONY : kernelcontainer.cpp.o

kernelcontainer.i: kernelcontainer.cpp.i

.PHONY : kernelcontainer.i

# target to preprocess a source file
kernelcontainer.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/kernelcontainer.cpp.i
.PHONY : kernelcontainer.cpp.i

kernelcontainer.s: kernelcontainer.cpp.s

.PHONY : kernelcontainer.s

# target to generate assembly for a file
kernelcontainer.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/kernelcontainer.cpp.s
.PHONY : kernelcontainer.cpp.s

map.o: map.cpp.o

.PHONY : map.o

# target to build an object file
map.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/map.cpp.o
.PHONY : map.cpp.o

map.i: map.cpp.i

.PHONY : map.i

# target to preprocess a source file
map.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/map.cpp.i
.PHONY : map.cpp.i

map.s: map.cpp.s

.PHONY : map.s

# target to generate assembly for a file
map.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/map.cpp.s
.PHONY : map.cpp.s

mapbase.o: mapbase.cpp.o

.PHONY : mapbase.o

# target to build an object file
mapbase.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/mapbase.cpp.o
.PHONY : mapbase.cpp.o

mapbase.i: mapbase.cpp.i

.PHONY : mapbase.i

# target to preprocess a source file
mapbase.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/mapbase.cpp.i
.PHONY : mapbase.cpp.i

mapbase.s: mapbase.cpp.s

.PHONY : mapbase.s

# target to generate assembly for a file
mapbase.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/mapbase.cpp.s
.PHONY : mapbase.cpp.s

noparallel.o: noparallel.cpp.o

.PHONY : noparallel.o

# target to build an object file
noparallel.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/noparallel.cpp.o
.PHONY : noparallel.cpp.o

noparallel.i: noparallel.cpp.i

.PHONY : noparallel.i

# target to preprocess a source file
noparallel.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/noparallel.cpp.i
.PHONY : noparallel.cpp.i

noparallel.s: noparallel.cpp.s

.PHONY : noparallel.s

# target to generate assembly for a file
noparallel.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/noparallel.cpp.s
.PHONY : noparallel.cpp.s

parallelk.o: parallelk.cpp.o

.PHONY : parallelk.o

# target to build an object file
parallelk.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/parallelk.cpp.o
.PHONY : parallelk.cpp.o

parallelk.i: parallelk.cpp.i

.PHONY : parallelk.i

# target to preprocess a source file
parallelk.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/parallelk.cpp.i
.PHONY : parallelk.cpp.i

parallelk.s: parallelk.cpp.s

.PHONY : parallelk.s

# target to generate assembly for a file
parallelk.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/parallelk.cpp.s
.PHONY : parallelk.cpp.s

poolschedule.o: poolschedule.cpp.o

.PHONY : poolschedule.o

# target to build an object file
poolschedule.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/poolschedule.cpp.o
.PHONY : poolschedule.cpp.o

poolschedule.i: poolschedule.cpp.i

.PHONY : poolschedule.i

# target to preprocess a source file
poolschedule.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/poolschedule.cpp.i
.PHONY : poolschedule.cpp.i

poolschedule.s: poolschedule.cpp.s

.PHONY : poolschedule.s

# target to generate assembly for a file
poolschedule.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/poolschedule.cpp.s
.PHONY : poolschedule.cpp.s

port.o: port.cpp.o

.PHONY : port.o

# target to build an object file
port.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/port.cpp.o
.PHONY : port.cpp.o

port.i: port.cpp.i

.PHONY : port.i

# target to preprocess a source file
port.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/port.cpp.i
.PHONY : port.cpp.i

port.s: port.cpp.s

.PHONY : port.s

# target to generate assembly for a file
port.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/port.cpp.s
.PHONY : port.cpp.s

port_info.o: port_info.cpp.o

.PHONY : port_info.o

# target to build an object file
port_info.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/port_info.cpp.o
.PHONY : port_info.cpp.o

port_info.i: port_info.cpp.i

.PHONY : port_info.i

# target to preprocess a source file
port_info.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/port_info.cpp.i
.PHONY : port_info.cpp.i

port_info.s: port_info.cpp.s

.PHONY : port_info.s

# target to generate assembly for a file
port_info.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/port_info.cpp.s
.PHONY : port_info.cpp.s

portexception.o: portexception.cpp.o

.PHONY : portexception.o

# target to build an object file
portexception.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/portexception.cpp.o
.PHONY : portexception.cpp.o

portexception.i: portexception.cpp.i

.PHONY : portexception.i

# target to preprocess a source file
portexception.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/portexception.cpp.i
.PHONY : portexception.cpp.i

portexception.s: portexception.cpp.s

.PHONY : portexception.s

# target to generate assembly for a file
portexception.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/portexception.cpp.s
.PHONY : portexception.cpp.s

portiterator.o: portiterator.cpp.o

.PHONY : portiterator.o

# target to build an object file
portiterator.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/portiterator.cpp.o
.PHONY : portiterator.cpp.o

portiterator.i: portiterator.cpp.i

.PHONY : portiterator.i

# target to preprocess a source file
portiterator.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/portiterator.cpp.i
.PHONY : portiterator.cpp.i

portiterator.s: portiterator.cpp.s

.PHONY : portiterator.s

# target to generate assembly for a file
portiterator.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/portiterator.cpp.s
.PHONY : portiterator.cpp.s

portmap_t.o: portmap_t.cpp.o

.PHONY : portmap_t.o

# target to build an object file
portmap_t.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/portmap_t.cpp.o
.PHONY : portmap_t.cpp.o

portmap_t.i: portmap_t.cpp.i

.PHONY : portmap_t.i

# target to preprocess a source file
portmap_t.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/portmap_t.cpp.i
.PHONY : portmap_t.cpp.i

portmap_t.s: portmap_t.cpp.s

.PHONY : portmap_t.s

# target to generate assembly for a file
portmap_t.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/portmap_t.cpp.s
.PHONY : portmap_t.cpp.s

pthreadwrap.o: pthreadwrap.c.o

.PHONY : pthreadwrap.o

# target to build an object file
pthreadwrap.c.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/pthreadwrap.c.o
.PHONY : pthreadwrap.c.o

pthreadwrap.i: pthreadwrap.c.i

.PHONY : pthreadwrap.i

# target to preprocess a source file
pthreadwrap.c.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/pthreadwrap.c.i
.PHONY : pthreadwrap.c.i

pthreadwrap.s: pthreadwrap.c.s

.PHONY : pthreadwrap.s

# target to generate assembly for a file
pthreadwrap.c.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/pthreadwrap.c.s
.PHONY : pthreadwrap.c.s

roundrobin.o: roundrobin.cpp.o

.PHONY : roundrobin.o

# target to build an object file
roundrobin.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/roundrobin.cpp.o
.PHONY : roundrobin.cpp.o

roundrobin.i: roundrobin.cpp.i

.PHONY : roundrobin.i

# target to preprocess a source file
roundrobin.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/roundrobin.cpp.i
.PHONY : roundrobin.cpp.i

roundrobin.s: roundrobin.cpp.s

.PHONY : roundrobin.s

# target to generate assembly for a file
roundrobin.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/roundrobin.cpp.s
.PHONY : roundrobin.cpp.s

schedule.o: schedule.cpp.o

.PHONY : schedule.o

# target to build an object file
schedule.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/schedule.cpp.o
.PHONY : schedule.cpp.o

schedule.i: schedule.cpp.i

.PHONY : schedule.i

# target to preprocess a source file
schedule.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/schedule.cpp.i
.PHONY : schedule.cpp.i

schedule.s: schedule.cpp.s

.PHONY : schedule.s

# target to generate assembly for a file
schedule.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/schedule.cpp.s
.PHONY : schedule.cpp.s

simpleschedule.o: simpleschedule.cpp.o

.PHONY : simpleschedule.o

# target to build an object file
simpleschedule.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/simpleschedule.cpp.o
.PHONY : simpleschedule.cpp.o

simpleschedule.i: simpleschedule.cpp.i

.PHONY : simpleschedule.i

# target to preprocess a source file
simpleschedule.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/simpleschedule.cpp.i
.PHONY : simpleschedule.cpp.i

simpleschedule.s: simpleschedule.cpp.s

.PHONY : simpleschedule.s

# target to generate assembly for a file
simpleschedule.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/simpleschedule.cpp.s
.PHONY : simpleschedule.cpp.s

stdalloc.o: stdalloc.cpp.o

.PHONY : stdalloc.o

# target to build an object file
stdalloc.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/stdalloc.cpp.o
.PHONY : stdalloc.cpp.o

stdalloc.i: stdalloc.cpp.i

.PHONY : stdalloc.i

# target to preprocess a source file
stdalloc.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/stdalloc.cpp.i
.PHONY : stdalloc.cpp.i

stdalloc.s: stdalloc.cpp.s

.PHONY : stdalloc.s

# target to generate assembly for a file
stdalloc.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/stdalloc.cpp.s
.PHONY : stdalloc.cpp.s

submap.o: submap.cpp.o

.PHONY : submap.o

# target to build an object file
submap.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/submap.cpp.o
.PHONY : submap.cpp.o

submap.i: submap.cpp.i

.PHONY : submap.i

# target to preprocess a source file
submap.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/submap.cpp.i
.PHONY : submap.cpp.i

submap.s: submap.cpp.s

.PHONY : submap.s

# target to generate assembly for a file
submap.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/submap.cpp.s
.PHONY : submap.cpp.s

systemsignalhandler.o: systemsignalhandler.cpp.o

.PHONY : systemsignalhandler.o

# target to build an object file
systemsignalhandler.cpp.o:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/systemsignalhandler.cpp.o
.PHONY : systemsignalhandler.cpp.o

systemsignalhandler.i: systemsignalhandler.cpp.i

.PHONY : systemsignalhandler.i

# target to preprocess a source file
systemsignalhandler.cpp.i:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/systemsignalhandler.cpp.i
.PHONY : systemsignalhandler.cpp.i

systemsignalhandler.s: systemsignalhandler.cpp.s

.PHONY : systemsignalhandler.s

# target to generate assembly for a file
systemsignalhandler.cpp.s:
	$(MAKE) -f CMakeFiles/raft.dir/build.make CMakeFiles/raft.dir/systemsignalhandler.cpp.s
.PHONY : systemsignalhandler.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... raft"
	@echo "... affinity.o"
	@echo "... affinity.i"
	@echo "... affinity.s"
	@echo "... allocate.o"
	@echo "... allocate.i"
	@echo "... allocate.s"
	@echo "... basicparallel.o"
	@echo "... basicparallel.i"
	@echo "... basicparallel.s"
	@echo "... common.o"
	@echo "... common.i"
	@echo "... common.s"
	@echo "... dynalloc.o"
	@echo "... dynalloc.i"
	@echo "... dynalloc.s"
	@echo "... fifo/Clock.o"
	@echo "... fifo/Clock.i"
	@echo "... fifo/Clock.s"
	@echo "... fifo/clockimpl.o"
	@echo "... fifo/clockimpl.i"
	@echo "... fifo/clockimpl.s"
	@echo "... fifo/fifo.o"
	@echo "... fifo/fifo.i"
	@echo "... fifo/fifo.s"
	@echo "... fifo/getrandom.o"
	@echo "... fifo/getrandom.i"
	@echo "... fifo/getrandom.s"
	@echo "... fifo/pointer.o"
	@echo "... fifo/pointer.i"
	@echo "... fifo/pointer.s"
	@echo "... fifo/procwait.o"
	@echo "... fifo/procwait.i"
	@echo "... fifo/procwait.s"
	@echo "... fifo/resolution.o"
	@echo "... fifo/resolution.i"
	@echo "... fifo/resolution.s"
	@echo "... fifo/shm.o"
	@echo "... fifo/shm.i"
	@echo "... fifo/shm.s"
	@echo "... fifo/signal.o"
	@echo "... fifo/signal.i"
	@echo "... fifo/signal.s"
	@echo "... fifo/signaldata.o"
	@echo "... fifo/signaldata.i"
	@echo "... fifo/signaldata.s"
	@echo "... fifo/systeminfo.o"
	@echo "... fifo/systeminfo.i"
	@echo "... fifo/systeminfo.s"
	@echo "... globalmap.o"
	@echo "... globalmap.i"
	@echo "... globalmap.s"
	@echo "... graphtools.o"
	@echo "... graphtools.i"
	@echo "... graphtools.s"
	@echo "... kernel.o"
	@echo "... kernel.i"
	@echo "... kernel.s"
	@echo "... kernelcontainer.o"
	@echo "... kernelcontainer.i"
	@echo "... kernelcontainer.s"
	@echo "... map.o"
	@echo "... map.i"
	@echo "... map.s"
	@echo "... mapbase.o"
	@echo "... mapbase.i"
	@echo "... mapbase.s"
	@echo "... noparallel.o"
	@echo "... noparallel.i"
	@echo "... noparallel.s"
	@echo "... parallelk.o"
	@echo "... parallelk.i"
	@echo "... parallelk.s"
	@echo "... poolschedule.o"
	@echo "... poolschedule.i"
	@echo "... poolschedule.s"
	@echo "... port.o"
	@echo "... port.i"
	@echo "... port.s"
	@echo "... port_info.o"
	@echo "... port_info.i"
	@echo "... port_info.s"
	@echo "... portexception.o"
	@echo "... portexception.i"
	@echo "... portexception.s"
	@echo "... portiterator.o"
	@echo "... portiterator.i"
	@echo "... portiterator.s"
	@echo "... portmap_t.o"
	@echo "... portmap_t.i"
	@echo "... portmap_t.s"
	@echo "... pthreadwrap.o"
	@echo "... pthreadwrap.i"
	@echo "... pthreadwrap.s"
	@echo "... roundrobin.o"
	@echo "... roundrobin.i"
	@echo "... roundrobin.s"
	@echo "... schedule.o"
	@echo "... schedule.i"
	@echo "... schedule.s"
	@echo "... simpleschedule.o"
	@echo "... simpleschedule.i"
	@echo "... simpleschedule.s"
	@echo "... stdalloc.o"
	@echo "... stdalloc.i"
	@echo "... stdalloc.s"
	@echo "... submap.o"
	@echo "... submap.i"
	@echo "... submap.s"
	@echo "... systemsignalhandler.o"
	@echo "... systemsignalhandler.i"
	@echo "... systemsignalhandler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

