Port Class Reference
Public Member Functions
Port (raft::kernel *const k)
Port (raft::kernel *const k, void *const ptr, const std::size_t nbytes)
virtual ~Port ()=default
template<class T , class... PORTNAMES>
void addPort (PORTNAMES &&... ports)
template<class T >
bool addInPlacePorts (const std::size_t n_ports)
const std::type_index & getPortType (const std::string &&port_name)
virtual FIFO & operator[] (const std::string &&port_name)
virtual bool hasPorts ()
virtual PortIterator begin ()
virtual PortIterator end ()
std::size_t count ()
template<class T >
void add_port (const std::string &port_name)
Protected Member Functions
template<class T >
void initializeConstMap (PortInfo &pi)
template<class T >
void initializeSplit (PortInfo &pi)
template<class T >
void initializeJoin (PortInfo &pi)
PortInfo & getPortInfo ()
PortInfo & getPortInfoFor (const std::string port_name)
Protected Attributes
portmap_t portmap
raft::kernel * kernel = nullptr
void *const alloc_ptr = nullptr
const std::size_t alloc_ptr_length = 0
Friends
class MapBase
class raft::map
class GraphTools
class basic_parallel
class raft::parallel_k
Detailed Description
Definition at line 106 of file port.hpp.
Constructor & Destructor Documentation
Port() [1/2]
Port::Port (raft::kernel *const k)
Port - constructor used to construct a standard port object, needs a reference to the parent kernel for the port_info struct
Parameters
k - raft::kernel*
port.cpp -
Author
: Jonathan Beard
Version
: Thu Aug 28 09:55:47 2014
Copyright 2014 Jonathan Beard
Licensed under the Apache License, Version 2.0 (the `License`); you may not use this file except in compliance with the License. You may obtain a copy of the License at:
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an `AS IS` BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Definition at line 32 of file port.cpp.
                                 : PortBase(),
                                       kernel(k)
{
}
Port() [2/2]
Port::Port (raft::kernel *const k, void *const ptr, const std::size_t nbytes)
Port - constructor used to construct a port with pre-allocated memory, useful for things like array distribution and reduction
Parameters
k - raft::kernel*
ptr - void*
nbytes - const std::size_t length in bytes
Definition at line 37 of file port.cpp.
                                     :
   PortBase(),
   kernel(k),
   alloc_ptr(ptr),
   alloc_ptr_length(nbytes)
{
}
 Port()
virtual Port::~Port () [virtual], [default]
~Port - destructor, deletes the FIFO that was given when the object was initalized.
Member Function Documentation
add_port()
template<class T >
void Port::add_port (const std::string & port_name) [inline]
add_port - adds and initializes a port for the name given. Function returns true if added, false if not. Main reason for returning false would be that the port already exists.
Parameters
port_name - const std::string
Returns
bool
we'll have to make a port info object first and pass it by copy to the portmap. Perhaps re-work later with pointers, but for right now this will work and it doesn't necessarily have to be performant since its only executed once.
Definition at line 244 of file port.hpp.
   {
      /**
       * we'll have to make a port info object first and pass it by copy
       * to the portmap. Perhaps re-work later with pointers, but for
       * right now this will work and it doesn't necessarily have to
       * be performant since its only executed once.
       */
      PortInfo pi(typeid(T));
      pi.my_kernel = kernel;
      pi.my_name = port_name;
      (this)->initializeConstMap<T>(pi);
      (this)->initializeSplit< T >(pi);
      (this)->initializeJoin< T >(pi);
      const auto ret_val(
                  portmap.map.insert(std::make_pair(port_name,
                                                      pi)));
      if(! ret_val.second)
      {
         throw PortAlreadyExists("FATAL ERROR: port \"" + port_name + "\" already exists!
      ");
      }
      return;
   }
addInPlacePorts()
template<class T >
bool Port::addInPlacePorts (const std::size_t n_ports) [inline]
addPorts - add ports for an existing buffer, basically allocate buffers in place. These also won't be able to be resized.
Parameters
n_ports - const std::size_t
pointer
gotta initialize the maps to copy stuff to/from
Definition at line 162 of file port.hpp.
   {
      T *existing_buff_t(reinterpret_cast< T* >(alloc_ptr));
      std::size_t length(alloc_ptr_length / sizeof(T));
      const std::size_t inc(length / n_ports);
      const std::size_t adder(length % n_ports);
      using index_type = std::remove_const_t<decltype(n_ports)>;
      for(index_type index(0); index < n_ports; index++)
      {
         const std::size_t start_index(index * inc);
         PortInfo pi(typeid(T),
                      (void*)&(existing_buff_t[ start_index ]) /** pointer **/,
                      inc + (index == (n_ports - 1) ? adder : 0),
                      start_index);
         pi.my_kernel = kernel;
         const std::string name(std::to_string(index));
         pi.my_name = name;
         /** gotta initialize the maps to copy stuff to/from **/
         (this)->initializeConstMap< T >(pi);
         (this)->initializeSplit< T >(pi);
         (this)->initializeJoin< T >(pi);
         portmap.map.insert(std::make_pair(name, pi));
      }
      return(true);
   }
addPort()
template<class T , class... PORTNAMES>
void Port::addPort (PORTNAMES &&... ports) [inline]
addPort - adds and initializes a port for the name given. Function returns true if added, false if not. Main reason for returning false would be that the port already exists.
Parameters
port_name - const std::string
Returns
bool
Definition at line 146 of file port.hpp.
Referenced by raft::parallel_k::addPortTo(), and start::run().
   {
       kick_port_helper< T, Port, PORTNAMES... >(
        (*this),
        std::forward< PORTNAMES >(ports)...);
   }
begin()
PortIterator Port::begin () [virtual]
begin - get the beginning port.
Returns
PortIterator
Implements PortBase.
Definition at line 82 of file port.cpp.
References portmap.
Referenced by raft::map::operator+=().
{
   return(PortIterator(&portmap));
}
count()
std::size_t Port::count ()
count - get the total number of fifos within this port container
Returns
std::size_t
Definition at line 94 of file port.cpp.
References portmap.
Referenced by raft::map::enableDuplication(), kpair::kpair(), raft::map::operator+=(), and basic_parallel::start().
{
   return((std::size_t) portmap.map.size());
}
end()
PortIterator Port::end () [virtual]
end - get the end port
Returns
PortIterator
Implements PortBase.
Definition at line 88 of file port.cpp.
References portmap.
Referenced by raft::map::operator+=().
{
   return(PortIterator(&portmap, portmap.map.size()));
}
getPortInfo()
PortInfo & Port::getPortInfo () [protected]
getPortInfo - returns the PortInfo struct for a kernel if we expect it to have a single port. If there's more than one port this function throws an exception.
Returns
std::pair< std::string, PortInfo& >
TODO: extract kernel name to go here too
Definition at line 113 of file port.cpp.
References portmap.
Referenced by MapBase::link(), and basic_parallel::start().
{
   if(portmap.map.size() > 1)
   {
      /** TODO: extract kernel name to go here too **/
      throw PortNotFoundException("One port expected, more than one found!");
   }
   auto pair(portmap.map.begin());
   return((*pair).second);
}
getPortInfoFor()
PortInfo & Port::getPortInfoFor (const std::string port_name) [protected]
getPortInfoFor - gets port information for the param port throws an exception if the port doesn't exist.
Parameters
port_name - const std::string
Returns
PortInfo&
Definition at line 100 of file port.cpp.
References portmap.
Referenced by GraphTools::BFS(), MapBase::join(), and MapBase::link().
{
   const auto ret_val(portmap.map.find(port_name));
   if(ret_val == portmap.map.cend())
   {
      std::stringstream ss;
      ss << "Port not found for name \"" << port_name << "\"";
      throw PortNotFoundException(ss.str());
   }
   return((*ret_val).second);
}
getPortType()
const std::type_index & Port::getPortType (const std::string && port_name)
getPortType - input the port name, and get the hash for the type of the port. This function is useful for checking the streaming graph to make sure all the ports that are `dynamically` created do in fact have compatible types.
Parameters
port_name - const std::string
Returns
const type_index&
Exceptions
PortNotFoundException
Definition at line 49 of file port.cpp.
References portmap.
{
   const auto ret_val(portmap.map.find(port_name));
   if(ret_val == portmap.map.cend())
   {
      throw PortNotFoundException("Port not found for name \"" + port_name + "\"");
   }
   return((*ret_val).second.type);
}
hasPorts()
bool Port::hasPorts () [virtual]
hasPorts - returns true if any ports exists, false otherwise.
Returns
bool
Implements PortBase.
Definition at line 76 of file port.cpp.
References portmap.
Referenced by Schedule::scheduleKernel(), and basic_parallel::start().
{
   return(portmap.map.size() > 0 ? true : false);
}
initializeConstMap()
template<class T >
void Port::initializeConstMap (PortInfo & pi) [inline], [protected]
initializeConstMap - hack to get around the inability to otherwise initialize a template function where later we don't have the template parameter. NOTE: this is a biggy, if we have more FIFO types in the future (i.e., sub-classes of FIFO) then we must create an entry here otherwise bad things will happen.
Parameters
pi - PortInfo&
no instrumentation
yes instrumentation
NOTE: If you define more port resource types, they have to be defined here...otherwise the allocator won't be able to allocate the correct type, size, etc. for the port..and well, it'll be sad.
Definition at line 279 of file port.hpp.
References PortInfo::const_map.
   {
      pi.const_map.insert(
         std::make_pair(Type::Heap , new instr_map_t()));
      pi.const_map[ Type::Heap ]->insert(
         std::make_pair(false /** no instrumentation **/,
                         RingBuffer< T, Type::Heap, false >::make_new_fifo));
      pi.const_map[ Type::Heap ]->insert(
         std::make_pair(true /** yes instrumentation **/,
                         RingBuffer< T, Type::Heap, true >::make_new_fifo));
      //pi.const_map.insert(std::make_pair(Type::SharedMemory, new instr_map_t()));
      //pi.const_map[ Type::SharedMemory ]->insert(
      // std::make_pair(false /** no instrumentation **/,
      // RingBuffer< T, Type::SharedMemory >::make_new_fifo));
      /**
       * NOTE: If you define more port resource types, they have
       * to be defined here...otherwise the allocator won't be
       * able to allocate the correct type, size, etc. for the
       * port..and well, it'll be sad.
       */
      return;
   }
initializeJoin()
template<class T >
void Port::initializeJoin (PortInfo & pi) [inline], [protected]
initializeJoin - pre-allocate join kernels...saves allocation time later, takes up minimal space and all that is needed when these are actually used is to allocate memory for the ports which is done by the
Definition at line 328 of file port.hpp.
   {
      pi.join_func =
         []() -> raft::kernel*
         {
            return(new raft::join< T, roundrobin >());
         };
      return;
   }
initializeSplit()
template<class T >
void Port::initializeSplit (PortInfo & pi) [inline], [protected]
initializeSplit - pre-allocate split kernels...saves allocation time later, then all that is needed is to hook them up, and allocate memory for the ports.
Definition at line 309 of file port.hpp.
References PortInfo::split_func.
   {
      pi.split_func =
         []() -> raft::kernel*
         {
            return(new raft::split< T, roundrobin >());
         };
      return;
   }
operator[]()
FIFO & Port::operator[] (const std::string && port_name) [virtual]
operator[] - input the port name and get a port if it exists.
Implements PortBase.
Definition at line 60 of file port.cpp.
References portmap.
{
   //NOTE: We'll need to add a lock here if later
   //we intend to remove ports dynamically as well
   //for the moment however lets just assume we're
   //only adding them
   const auto ret_val(portmap.map.find(port_name));
   if(ret_val == portmap.map.cend())
   {
      throw PortNotFoundException(
         "Port not found for name \"" + port_name + "\"");
   }
   return(*((*ret_val).second.getFIFO()));
}
Friends And Related Function Documentation
MapBase
friend class MapBase [friend]
we need some friends
Definition at line 379 of file port.hpp.
Member Data Documentation
alloc_ptr
void* const Port::alloc_ptr = nullptr [protected]
ptr used for in-place allocations, will not be deleted by the map, also should not be modified by the map either.
Definition at line 370 of file port.hpp.
alloc_ptr_length
const std::size_t Port::alloc_ptr_length = 0 [protected]
alloc_ptr_length - length of alloc_ptr in bytes.
Definition at line 376 of file port.hpp.
kernel
raft::kernel* Port::kernel = nullptr [protected]
parent kernel that owns this port
Definition at line 363 of file port.hpp.
portmap
portmap_t Port::portmap [protected]
portmap - container struct with all ports. The mutex should be locked before accessing this structure
Definition at line 358 of file port.hpp.
Referenced by begin(), GraphTools::BFS(), count(), end(), getPortInfo(), getPortInfoFor(), getPortType(), hasPorts(), and operator[]().
The documentation for this class was generated from the following files:
port.hpp
port.cpp