GraphTools Class Reference
Static Public Member Functions
static void BFS (std::set< raft::kernel * > &source_kernels, edge_func func, void *data=nullptr, bool connected_error=false)
static void BFS (std::vector< raft::kernel * > &source_kernels, edge_func func, void *data=nullptr, bool connected_error=false)
static void BFS (std::set< raft::kernel * > &source_kernels, vertex_func func, void *data)
Detailed Description
Definition at line 56 of file graphtools.hpp.
Member Function Documentation
BFS() [1/2]
void GraphTools::BFS (std::set< raft::kernel * > & source_kernels, edge_func func, void * data = nullptr, bool connected_error = false) [static]
BFS - perform a breadth first search of the graph given by 'source_kernels'. The function 'func' matches the typedef above and is called on each edge of the graph exactly once. For state between calls, the user can define a data struct and pass it via the void ptr data which is passed to the func.
Parameters
source_kernels - set of source kernels.
func - edge_func, funciton to be called
data - void*, data struct for persistent state
connected_error,throw an error if not connected
graphtools.cpp -
Author
: Jonathan Beard
Version
: Sat Sep 20 13:15:09 2014
Copyright 2014 Jonathan Beard
Licensed under the Apache License, Version 2.0 (the `License`); you may not use this file except in compliance with the License. You may obtain a copy of the License at:
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an `AS IS` BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Definition at line 38 of file graphtools.cpp.
Referenced by BFS(), raft::map::checkEdges(), raft::map::enableDuplication(), dynalloc::run(), stdalloc::run(), and basic_parallel::start().
{
   std::set< raft::kernel* > visited_set;
   std::queue< raft::kernel* > queue;
   std::for_each(source_kernels.begin(),
                  source_kernels.end(),
                  [&](raft::kernel *k)
                  {
                     queue.push(k);
                     visited_set.insert(k);
                  });
   GraphTools::__BFS(queue, visited_set, func, data, connected_error);
}
BFS() [2/2]
void GraphTools::BFS (std::vector< raft::kernel * > & source_kernels, edge_func func, void * data = nullptr, bool connected_error = false) [static]
BFS - perform a breadth first search of the graph given by 'source_kernels'. The function 'func' matches the typedef above and is called on each edge of the graph exactly once. For state between calls, the user can define a data struct and pass it via the void ptr data which is passed to the func.
Parameters
source_kernels - set of source kernels.
func - edge_func, funciton to be called
data - void*, data struct for persistent state
connected_error,throw an error if not connected
Definition at line 56 of file graphtools.cpp.
References BFS(), Port::getPortInfoFor(), raft::kernel::input, Port::portmap, and common::printClassName().
{
   std::set< raft::kernel* > visited_set;
   std::queue< raft::kernel* > queue;
   std::for_each(source_kernels.begin(),
                  source_kernels.end(),
                  [&](raft::kernel *k)
                  {
                     queue.push(k);
                     visited_set.insert(k);
                  });
   GraphTools::__BFS(queue, visited_set, func, data, connected_error);
}
The documentation for this class was generated from the following files:
graphtools.hpp
graphtools.cpp