MapBase Class Reference
#include <mapbase.hpp>
Public Member Functions
MapBase ()
virtual ~MapBase ()
template<raft::order::spec t = raft::order::in>
kernel_pair_t link (raft::kernel *a, raft::kernel *b, const std::size_t buffer=0)
template<raft::order::spec t = raft::order::in>
kernel_pair_t link (raft::kernel *a, const std::string a_port, raft::kernel *b, const std::size_t buffer=0)
template<raft::order::spec t = raft::order::in>
kernel_pair_t link (raft::kernel *a, raft::kernel *b, const std::string b_port, const std::size_t buffer=0)
template<raft::order::spec t = raft::order::in>
kernel_pair_t link (raft::kernel *a, const std::string a_port, raft::kernel *b, const std::string b_port, const std::size_t buffer=0)
Protected Member Functions
template<class A , class B >
void updateKernels (A &a, B &b)
Static Protected Member Functions
static void join (raft::kernel &a, const std::string name_a, PortInfo &a_info, raft::kernel &b, const std::string name_b, PortInfo &b_info)
static void insert (raft::kernel *a, PortInfo &a_out, raft::kernel *b, PortInfo &b_in, raft::kernel *i)
template<raft::order::spec t, typename std::enable_if< t==raft::order::in >::type * = nullptr>
static void set_order (PortInfo &port_info_a, PortInfo &port_info_b) noexcept
template<raft::order::spec t, typename std::enable_if< t==raft::order::out >::type * = nullptr>
static void set_order (PortInfo &port_info_a, PortInfo &port_info_b) noexcept
static void portNotFound (bool src, PortNotFoundException &ex, raft::kernel *const k)
Protected Attributes
kernelkeeper source_kernels
kernelkeeper dst_kernels
kernelkeeper all_kernels
std::vector< MapBase *> sub_maps
Friends
class raft::map
Detailed Description
mapbase.hpp - Base map object. The general idea is that the map object will contain everything needed to construct a streaming topology. There are two sub-classes. One is the final `map` topology, the other is the kernel map topology. The `kernel map` variant has no exe functions nor map checking functions. It is assumed that the `kernel map` derivative is contained within a kernel which might have several sub `kernels` within it.
Author
: Jonathan Beard
Version
: Fri Sep 12 10:28:33 2014
Copyright 2014 Jonathan Beard
Licensed under the Apache License, Version 2.0 (the `License`); you may not use this file except in compliance with the License. You may obtain a copy of the License at:
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an `AS IS` BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Definition at line 51 of file mapbase.hpp.
Constructor & Destructor Documentation
MapBase()
MapBase::MapBase ()
MapBase - constructor, really doesn't do too much at the monent and doesn't really need to.
mapbase.cpp -
Author
: Jonathan Beard
Version
: Fri Sep 12 10:28:33 2014
Copyright 2014 Jonathan Beard
Licensed under the Apache License, Version 2.0 (the `License`); you may not use this file except in compliance with the License. You may obtain a copy of the License at:
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an `AS IS` BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Definition at line 35 of file mapbase.cpp.
{
  
}
 MapBase()
MapBase::~MapBase () [virtual]
default destructor
Definition at line 40 of file mapbase.cpp.
References all_kernels.
{
   auto &container(all_kernels.acquire());
   for(raft::kernel *kern : container)
   {
      if(kern != nullptr && kern->internal_alloc)
      {
         if(kern->internal_alloc)
         {
            delete(kern);
         }
      }
   }
   all_kernels.release();
}
Member Function Documentation
join()
void MapBase::join (raft::kernel & a, const std::string name_a, PortInfo & a_info, raft::kernel & b, const std::string name_b, PortInfo & b_info) [static], [protected]
join - helper method joins the two ports given the correct information. Essentially the correct information for the PortInfo object is set. Type is also checked using the typeid information. If the types aren't the same then an exception is thrown.
Parameters
a - raft::kernel&
name_a - name for the port on kernel a
a_info - PortInfo struct for kernel a
b - raft::kernel&
name_b - name for port on kernel b
b_info - PortInfo struct for kernel b
Exceptions
PortTypeMismatchException
Definition at line 58 of file mapbase.cpp.
References Port::getPortInfoFor(), raft::kernel::input, common::printClassName(), and PortInfo::type.
Referenced by raft::map::enableDuplication(), link(), and raft::map::operator+=().
{
   //b's port info isn't allocated
   if(a_info.type != b_info.type)
   {
      std::stringstream ss;
      ss << "When attempting to join ports (" << common::printClassName(a) <<
         "[" << name_a << "] -> " << common::printClassName(b) << "[" <<
         name_b << "] have conflicting types. " <<
            common::printClassNameFromStr(a_info.type.name()) <<
         " and " << common::printClassNameFromStr(b_info.type.name()) << "\n";
      throw PortTypeMismatchException(ss.str());
   }
   a_info.other_kernel = &b;
   a_info.other_name = name_b;
   b_info.other_kernel = &a;
   b_info.other_name = name_a;
}
link() [1/4]
template<raft::order::spec t = raft::order::in>
kernel_pair_t MapBase::link (raft::kernel * a, raft::kernel * b, const std::size_t buffer = 0) [inline]
link - this comment goes for the next 4 types of link functions, which basically do the exact same thing. The template function takes a single param order::spec which is exactly as the name implies, the order of the queue linking the two kernels. The various functions are needed to specify different ordering types each of these will be commented separately below. This function assumes that Kernel 'a' has only a single output and raft::kernel 'b' has only a single input otherwise an exception will be thrown.
Parameters
a - raft::kernel*, src kernel
b - raft::kernel*, dst kernel
Exceptions
AmbiguousPortAssignmentException - thrown if either src or dst have more than a single port to link.
Returns
kernel_pair_t - references to src, dst kernels.
Definition at line 82 of file mapbase.hpp.
References Port::getPortInfo(), raft::kernel::input, and join().
Referenced by raft::map::joink(), and display< T >::run().
   {
      updateKernels(a, b);
      PortInfo *port_info_a;
      try{
         port_info_a = &(a->output.getPortInfo());
      }
      catch(PortNotFoundException &ex)
      {
         portNotFound(true,
                       ex,
                       a);
      }
      port_info_a->fixed_buffer_size = buffer;
      PortInfo *port_info_b;
      try{
         port_info_b = &(b->input.getPortInfo());
      }
      catch(PortNotFoundException &ex)
      {
            portNotFound(false,
                          ex,
                          b);
      }
      port_info_b->fixed_buffer_size = buffer;
      join(*a, port_info_a->my_name, *port_info_a,
            *b, port_info_b->my_name, *port_info_b);
      set_order< t >(*port_info_a, *port_info_b);
      return(kernel_pair_t(a, b));
   }
link() [2/4]
template<raft::order::spec t = raft::order::in>
kernel_pair_t MapBase::link (raft::kernel * a, const std::string a_port, raft::kernel * b, const std::size_t buffer = 0) [inline]
link - same as function above save for the following differences: kernel a is assumed to have multiple ports and the one we wish to link with raft::kernel b is a_port. raft::kernel b is assumed to have a single input port to connect otherwise an exception is thrown.
Parameters
a - raft::kernel *a, can have multiple ports
a_port - port within raft::kernel a to link
b - raft::kernel *b, assumed to have only single input.
Exceptions
AmbiguousPortAssignmentException - thrown if raft::kernel b has more than a single input port.
PortNotFoundException - thrown if raft::kernel a has no port named a_port.
Returns
kernel_pair_t - references to src, dst kernels.
Definition at line 131 of file mapbase.hpp.
References Port::getPortInfo(), Port::getPortInfoFor(), raft::kernel::input, and join().
   {
      updateKernels(a, b);
      PortInfo &port_info_a(a->output.getPortInfoFor(a_port));
      port_info_a.fixed_buffer_size = buffer;
      PortInfo *port_info_b;
      try{
         port_info_b = &(b->input.getPortInfo());
      }
      catch(PortNotFoundException &ex)
      {
            portNotFound(false,
                          ex,
                          b);
      }
      port_info_b->fixed_buffer_size = buffer;
      join(*a, a_port , port_info_a,
            *b, port_info_b->my_name, *port_info_b);
      set_order< t >(port_info_a, *port_info_b);
      return(kernel_pair_t(a, b));
   }
link() [3/4]
template<raft::order::spec t = raft::order::in>
kernel_pair_t MapBase::link (raft::kernel * a, raft::kernel * b, const std::string b_port, const std::size_t buffer = 0) [inline]
link - same as above save for the following differences: raft::kernel a is assumed to have a single output port. raft::kernel b is assumed to have more than one input port, within one matching the port b_port.
Parameters
a - raft::kernel*, with more a single output port
b - raft::kernel*, with input port named b_port
b_port - const std::string, input port name.
Exceptions
AmbiguousPortAssignmentException - exception thrown if raft::kernel a has more than a single output port
PortNotFoundException - exception thrown if raft::kernel b has no input port named b_port
Returns
kernel_pair_t - references to src, dst kernels.
Definition at line 172 of file mapbase.hpp.
References Port::getPortInfo(), Port::getPortInfoFor(), raft::kernel::input, and join().
   {
      updateKernels(a, b);
      PortInfo *port_info_a;
      try{
         port_info_a = &(a->output.getPortInfo());
      }
      catch(PortNotFoundException &ex)
      {
            portNotFound(true,
                          ex,
                          a);
      }
      port_info_a->fixed_buffer_size = buffer;
      
      PortInfo &port_info_b(b->input.getPortInfoFor(b_port));
      port_info_b.fixed_buffer_size = buffer;
      
      join(*a, port_info_a->my_name, *port_info_a,
            *b, b_port, port_info_b);
      set_order< t >(*port_info_a, port_info_b);
      return(kernel_pair_t(a, b));
   }
link() [4/4]
template<raft::order::spec t = raft::order::in>
kernel_pair_t MapBase::link (raft::kernel * a, const std::string a_port, raft::kernel * b, const std::string b_port, const std::size_t buffer = 0) [inline]
link - same as above save for the following differences: raft::kernel a is assumed to have an output port a_port and raft::kernel b is assumed to have an input port b_port.
Parameters
a - raft::kernel*, with more a single output port
a_port - const std::string, output port name
b - raft::kernel*, with input port named b_port
b_port - const std::string, input port name.
Exceptions
PortNotFoundException - exception thrown if either kernel is missing port a_port or b_port.
Returns
kernel_pair_t - references to src, dst kernels.
Definition at line 212 of file mapbase.hpp.
References Port::getPortInfoFor(), raft::kernel::input, and join().
   {
      updateKernels(a, b);
      auto &port_info_a(a->output.getPortInfoFor(a_port));
      port_info_a.fixed_buffer_size = buffer;
      auto &port_info_b(b->input.getPortInfoFor(b_port));
      port_info_b.fixed_buffer_size = buffer;
      
      join(*a, a_port, port_info_a,
            *b, b_port, port_info_b);
      set_order< t >(port_info_a, port_info_b);
      return(kernel_pair_t(a, b));
   }
set_order() [1/2]
template<raft::order::spec t, typename std::enable_if< t==raft::order::in >::type * = nullptr>
static void MapBase::set_order (PortInfo & port_info_a, PortInfo & port_info_b) [inline], [static], [protected], [noexcept]
set_order - keep redundant code, well, less redundant. This version handles the in-order settings.
Parameters
port_info_a,PortInfo&
port_info_b,PortInfo&
Definition at line 264 of file mapbase.hpp.
   {
        port_info_a.out_of_order = false;
        port_info_b.out_of_order = false;
        return;
   }
set_order() [2/2]
template<raft::order::spec t, typename std::enable_if< t==raft::order::out >::type * = nullptr>
static void MapBase::set_order (PortInfo & port_info_a, PortInfo & port_info_b) [inline], [static], [protected], [noexcept]
set_order - keep redundant code, well, less redundant. This version handles the out-of-order settings.
Parameters
port_info_a,PortInfo&
port_info_b,PortInfo&
Definition at line 281 of file mapbase.hpp.
References all_kernels, dst_kernels, and source_kernels.
   {
        port_info_a.out_of_order = true;
        port_info_b.out_of_order = true;
        return;
   }
Member Data Documentation
all_kernels
kernelkeeper MapBase::all_kernels [protected]
and keep a list of all kernels
Definition at line 332 of file mapbase.hpp.
Referenced by raft::map::exe(), set_order(), and ~MapBase().
dst_kernels
kernelkeeper MapBase::dst_kernels [protected]
dst kernels
Definition at line 330 of file mapbase.hpp.
Referenced by set_order().
source_kernels
kernelkeeper MapBase::source_kernels [protected]
need to keep source kernels
Definition at line 328 of file mapbase.hpp.
Referenced by raft::map::exe(), and set_order().
sub_maps
std::vector< MapBase* > MapBase::sub_maps [protected]
FIXME: come up with better solution for enabling online duplication of submaps as a unit.
DOES: flatten these kernels into main map once we run
Definition at line 339 of file mapbase.hpp.
Referenced by raft::map::exe().
The documentation for this class was generated from the following files:
mapbase.hpp
mapbase.cpp