dynalloc Class Reference
Public Member Functions
dynalloc (raft::map &map, volatile bool &exit_alloc)
virtual void run ()
Additional Inherited Members
Detailed Description
Definition at line 29 of file dynalloc.hpp.
Constructor & Destructor Documentation
dynalloc()
dynalloc::dynalloc (raft::map & map, volatile bool & exit_alloc)
dynalloc.cpp -
Author
: Jonathan Beard
Version
: Mon Oct 13 16:36:18 2014
Copyright 2014 Jonathan Beard
Licensed under the Apache License, Version 2.0 (the `License`); you may not use this file except in compliance with the License. You may obtain a copy of the License at:
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an `AS IS` BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Definition at line 35 of file dynalloc.cpp.
                                                :
                        Allocate(map, exit_alloc)
{
}
Member Function Documentation
run()
void dynalloc::run () [virtual]
run - call to initiate schedule, in the current instantiation this is called by the scheduler. same alloc for all, inherit from base alloc
acquire source kernels
make this a fixed quantity right now, if size > .75% at montor interval three times or more then increase size.
TODO, the values might wrap if no monitoring on
get initializer function
start monitor loop
monitor fifo's
Implements Allocate.
Definition at line 65 of file dynalloc.cpp.
References GraphTools::BFS(), Allocate::exit_alloc, FIFO::get_frac_write_blocked(), PortInfo::getFIFO(), Allocate::setReady(), and Allocate::source_kernels.
{
   auto alloc_func = [&](PortInfo &a, PortInfo &b, void *data)
   {
      /** same alloc for all, inherit from base alloc **/
      (this)->allocate(a, b, data);
   };
   /** acquire source kernels **/
   auto &container((this)->source_kernels.acquire());
   GraphTools::BFS(container, alloc_func);
   (this)->source_kernels.release();
   (this)->setReady();
   std::map< std::size_t, int > size_map;
   /**
    * make this a fixed quantity right now, if size > .75% at
    * montor interval three times or more then increase size.
    */
   auto mon_func = [&](PortInfo &a, PortInfo &b, void *data) -> void
   {
      (void) data;
      const auto hash_val(dynalloc::hash(a, b));
      /** TODO, the values might wrap if no monitoring on **/
      const auto realized_ratio(a.getFIFO()->get_frac_write_blocked());
      const auto ratio(0.8);
      if(realized_ratio >= ratio)
      {
         const auto curr_count(size_map[ hash_val ]++);
         if(curr_count > 2)
         {
            /** get initializer function **/
            auto * const buff_ptr(a.getFIFO());
            const auto cap(buff_ptr->capacity());
            buff_ptr->resize(cap * 2, ALLOC_ALIGN_WIDTH, exit_alloc);
            size_map[ hash_val ] = 0;
         }
      }
      return;
   };
   /** start monitor loop **/
   while(! exit_alloc)
   {
      /** monitor fifo's **/
      std::chrono::microseconds dura(3000);
      std::this_thread::sleep_for(dura);
      auto &container((this)->source_kernels.acquire());
      GraphTools::BFS(container, mon_func);
      (this)->source_kernels.release();
   }
   return;
}
The documentation for this class was generated from the following files:
dynalloc.hpp
dynalloc.cpp