kernel_pair_t Class Reference
#include <kernel_pair_t.hpp>
Public Types
using kernel_iterator_type = kernel_pair_t_container::iterator
using endpoint_ret_type = std::pair< kernel_iterator_type, kernel_iterator_type >
using size_type = typename kernel_pair_t_container::size_type
Public Member Functions
kernel_pair_t ()
kernel_pair_t (raft::kernel *const src, raft::kernel *const dst)
kernel_pair_t (raft::kernel &src, raft::kernel &dst)
kernel_pair_t::endpoint_ret_type getSrc ()
kernel_pair_t::size_type getSrcSize () noexcept
kernel_pair_t::endpoint_ret_type getDst ()
kernel_pair_t::size_type getDstSize () noexcept
void addSrc (raft::kernel &k) noexcept
void addDst (raft::kernel &k) noexcept
void clearSrc () noexcept
void clearDst () noexcept
Detailed Description
basic idea here is that we want a return type for the link() function calls as well as the operator += overload on the map that enables return of multiple compute kernels for the user to stitch together in another invocation to add more kernels to the map. What we also want to ensure is that there is no way for the user to delete one of these kernels which could create for some interesting bugs. the std::pair seems like an obvious choice to return, however creating a container as part of the std::pair is a bit hacky so we'll use the container directly, the next consideration is what type of container to use inside that std::pair which should be expandable. Again, the obvious choice seems like it should be the std::vector which needs to hold references so they can't be easily deleted..which means we'll have to use std::reference_wrapper as well.n
Definition at line 56 of file kernel_pair_t.hpp.
Member Typedef Documentation
endpoint_ret_type
using kernel_pair_t::endpoint_ret_type = std::pair< kernel_iterator_type, kernel_iterator_type >
endpoint ret type is a std::pair with two iterators, one for begin, the second for end
Definition at line 74 of file kernel_pair_t.hpp.
kernel_iterator_type
using kernel_pair_t::kernel_iterator_type = kernel_pair_t_container::iterator
define iterator type publicly
Definition at line 66 of file kernel_pair_t.hpp.
size_type
using kernel_pair_t::size_type = typename kernel_pair_t_container::size_type
define a size type that matches the container type, whatever that container type may end up being
Definition at line 80 of file kernel_pair_t.hpp.
Constructor & Destructor Documentation
kernel_pair_t() [1/3]
kernel_pair_t::kernel_pair_t ()
kernel_pair_t - default constructor, simply reserves some space for the container, assumes container has a reserve(xx) function to call in the first place...likely need to add a enable_if to make sure that is always the case TODO, might need to optimize with something better
Definition at line 3 of file kernel_pair_t.cpp.
{
    /** TODO, might need to optimize with something better **/
    source.reserve(2);
    destination.reserve(2);
}
kernel_pair_t() [2/3]
kernel_pair_t::kernel_pair_t (raft::kernel *const src, raft::kernel *const dst)
kernel_pair_t - construct by first calling the base constructor, then insert into the containers with the parameters of this constructor.
Parameters
src - raft;:kernel, source kernel
dst - raft::kernel, destination kernel
Definition at line 10 of file kernel_pair_t.cpp.
                                                       : kernel_pair_t()
{
    source.emplace_back(*src);
    destination.emplace_back(*dst);
}
kernel_pair_t() [3/3]
kernel_pair_t::kernel_pair_t (raft::kernel & src, raft::kernel & dst)
kernel_pair_t - construct by first calling the base constructor, then insert into the containers with the parameters of this constructor.
Parameters
src - raft;:kernel, source kernel
dst - raft::kernel, destination kernel
Definition at line 18 of file kernel_pair_t.cpp.
                                                : kernel_pair_t()
{
    source.emplace_back(src);
    destination.emplace_back(dst);
}
Member Function Documentation
addDst()
void kernel_pair_t::addDst (raft::kernel & k) [noexcept]
addDst - add a destination kernel to this pair object which is retreivable by the getDst. If this object disappears (is deallocated) after you add it then bad things might happen...don't delete them till you've disposed of these objects.
Parameters
k - raft::kernel&
Definition at line 57 of file kernel_pair_t.cpp.
Referenced by raft::map::operator+=().
{
    destination.emplace_back(k);
}
addSrc()
void kernel_pair_t::addSrc (raft::kernel & k) [noexcept]
addSrc - add a source kernel to this pair object which is retreivable by the getSrc. If this object disappears (is deallocated) after you add it then bad things might happen...don't delete them till you've disposed of these objects.
Parameters
k - raft::kernel&
Definition at line 51 of file kernel_pair_t.cpp.
Referenced by raft::map::operator+=().
{
    source.emplace_back(k);
}
clearDst()
void kernel_pair_t::clearDst () [noexcept]
clearDst - does exactly what it says, clears out the list of kernels, does not however destoy them so they're still valid kernels, just not available to the list anymore
Definition at line 69 of file kernel_pair_t.cpp.
{
    destination.clear();
}
clearSrc()
void kernel_pair_t::clearSrc () [noexcept]
clearSrc - does exactly what it says, clears out the list of kernels, does not however destoy them so they're still valid kernels, just not available to the list anymore
Definition at line 63 of file kernel_pair_t.cpp.
Referenced by raft::map::operator+=().
{
    source.clear();
}
getDst()
kernel_pair_t::endpoint_ret_type kernel_pair_t::getDst ()
getDst - return a std::pair object with iterators to the dst list of kernels added in the last map addition. Again, pair.first maps ot begin(), and pair.second maps to end();
Returns
endpoint_ret_type
Definition at line 39 of file kernel_pair_t.cpp.
{
    return(endpoint_ret_type(destination.begin(), destination.end()));
}
getDstSize()
kernel_pair_t::size_type kernel_pair_t::getDstSize () [noexcept]
getDstSize - returns the size of the destination container. This is the number of kernels within the last map addition.
Returns
size_type - number of kernels in source container
Definition at line 45 of file kernel_pair_t.cpp.
{
    return(destination.size());
}
getSrc()
kernel_pair_t::endpoint_ret_type kernel_pair_t::getSrc ()
getSrc - return a std::pair object with iterators to the source and destination of the list of sources added in the last map addition. Again, pair.first maps ot begin(), and pair.second maps to end();
Returns
endpoint_ret_type
Definition at line 26 of file kernel_pair_t.cpp.
{
    return(endpoint_ret_type(source.begin(), source.end()));
}
getSrcSize()
kernel_pair_t::size_type kernel_pair_t::getSrcSize () [noexcept]
getSrcSize - returns the size of the source container. This is the number of kernels within the last map addition.
Returns
size_type - number of kernels in source container
Definition at line 32 of file kernel_pair_t.cpp.
{
    return(source.size());
}
The documentation for this class was generated from the following files:
kernel_pair_t.hpp
kernel_pair_t.cpp