sub< T > Class Template Reference
Public Member Functions
sub (const sub< T > &other)
CLONE ()
virtual raft::kstatus run ()
sub (const sub< T > &other)
CLONE ()
virtual raft::kstatus run ()
sub (const sub< T > &other)
CLONE ()
virtual raft::kstatus run ()
sub (const sub< T > &other)
CLONE ()
virtual raft::kstatus run ()
sub (const sub< T > &other)
CLONE ()
virtual raft::kstatus run ()
sub (const sub< T > &other)
CLONE ()
virtual raft::kstatus run ()
sub (const sub< T > &other)
CLONE ()
virtual raft::kstatus run ()
sub (const sub< T > &other)
CLONE ()
virtual raft::kstatus run ()
sub (const sub< T > &other)
CLONE ()
virtual raft::kstatus run ()
sub (const sub< T > &other)
CLONE ()
virtual raft::kstatus run ()
sub (const sub< T > &other)
CLONE ()
virtual raft::kstatus run ()
sub (const sub< T > &other)
CLONE ()
virtual raft::kstatus run ()
Additional Inherited Members
Detailed Description
template<class T>
class sub< T >
Definition at line 31 of file splitchain.cpp.
Member Function Documentation
run() [1/12]
template<class T>
virtual raft::kstatus sub< T >::run () [inline], [virtual]
run - function to be extended for the actual execution. Code can be executed outside of the run function, i.e., with any function call, however the scheduler will only call the run function so it must initiate any follow-on behavior desired by the user.
Implements raft::kernel.
Definition at line 48 of file staticContJoin.cpp.
References raft::map::exe(), and raft::kernel::input.
    {
        T a;
        input[ "0" ].pop(a);
        output[ "0" ].push(a - 10);
        return(raft::proceed);
    }
run() [2/12]
template<class T>
virtual raft::kstatus sub< T >::run () [inline], [virtual]
run - function to be extended for the actual execution. Code can be executed outside of the run function, i.e., with any function call, however the scheduler will only call the run function so it must initiate any follow-on behavior desired by the user.
Implements raft::kernel.
Definition at line 48 of file staticSplitChainJoin.cpp.
References raft::map::exe(), and raft::kernel::input.
    {
        T a;
        input[ "0" ].pop(a);
        output[ "0" ].push(a - 10);
        return(raft::proceed);
    }
run() [3/12]
template<class T>
virtual raft::kstatus sub< T >::run () [inline], [virtual]
run - function to be extended for the actual execution. Code can be executed outside of the run function, i.e., with any function call, however the scheduler will only call the run function so it must initiate any follow-on behavior desired by the user.
Implements raft::kernel.
Definition at line 48 of file staticSplitChainJoinRetStruct.cpp.
References raft::map::exe(), and raft::kernel::input.
    {
        T a;
        input[ "0" ].pop(a);
        output[ "0" ].push(a - 10);
        return(raft::proceed);
    }
run() [4/12]
template<class T>
virtual raft::kstatus sub< T >::run () [inline], [virtual]
run - function to be extended for the actual execution. Code can be executed outside of the run function, i.e., with any function call, however the scheduler will only call the run function so it must initiate any follow-on behavior desired by the user.
Implements raft::kernel.
Definition at line 48 of file staticJoin.cpp.
References raft::map::exe(), and raft::kernel::input.
    {
        T a;
        input[ "0" ].pop(a);
        output[ "0" ].push(a - 10);
        return(raft::proceed);
    }
run() [5/12]
template<class T>
virtual raft::kstatus sub< T >::run () [inline], [virtual]
run - function to be extended for the actual execution. Code can be executed outside of the run function, i.e., with any function call, however the scheduler will only call the run function so it must initiate any follow-on behavior desired by the user.
Implements raft::kernel.
Definition at line 48 of file staticSplitJoinRetStruct.cpp.
References raft::map::exe(), and raft::kernel::input.
    {
        T a;
        input[ "0" ].pop(a);
        output[ "0" ].push(a - 10);
        return(raft::proceed);
    }
run() [6/12]
template<class T>
virtual raft::kstatus sub< T >::run () [inline], [virtual]
run - function to be extended for the actual execution. Code can be executed outside of the run function, i.e., with any function call, however the scheduler will only call the run function so it must initiate any follow-on behavior desired by the user.
Implements raft::kernel.
Definition at line 48 of file staticSplitJoin.cpp.
References raft::map::exe(), and raft::kernel::input.
    {
        T a;
        input[ "0" ].pop(a);
        output[ "0" ].push(a - 10);
        return(raft::proceed);
    }
run() [7/12]
template<class T>
virtual raft::kstatus sub< T >::run () [inline], [virtual]
run - function to be extended for the actual execution. Code can be executed outside of the run function, i.e., with any function call, however the scheduler will only call the run function so it must initiate any follow-on behavior desired by the user.
Implements raft::kernel.
Definition at line 48 of file staticLongSplitChain.cpp.
References raft::map::exe(), and raft::kernel::input.
    {
        T a;
        input[ "0" ].pop(a);
        output[ "0" ].push(a - 10);
        return(raft::proceed);
    }
run() [8/12]
template<class T>
virtual raft::kstatus sub< T >::run () [inline], [virtual]
run - function to be extended for the actual execution. Code can be executed outside of the run function, i.e., with any function call, however the scheduler will only call the run function so it must initiate any follow-on behavior desired by the user.
Implements raft::kernel.
Definition at line 48 of file staticJoinRetStruct.cpp.
References raft::map::exe(), and raft::kernel::input.
    {
        T a;
        input[ "0" ].pop(a);
        output[ "0" ].push(a - 10);
        return(raft::proceed);
    }
run() [9/12]
template<class T>
virtual raft::kstatus sub< T >::run () [inline], [virtual]
run - function to be extended for the actual execution. Code can be executed outside of the run function, i.e., with any function call, however the scheduler will only call the run function so it must initiate any follow-on behavior desired by the user.
Implements raft::kernel.
Definition at line 48 of file staticLongSplitChainRetStruct.cpp.
References raft::map::exe(), and raft::kernel::input.
    {
        T a;
        input[ "0" ].pop(a);
        output[ "0" ].push(a - 10);
        return(raft::proceed);
    }
run() [10/12]
template<class T>
virtual raft::kstatus sub< T >::run () [inline], [virtual]
run - function to be extended for the actual execution. Code can be executed outside of the run function, i.e., with any function call, however the scheduler will only call the run function so it must initiate any follow-on behavior desired by the user.
Implements raft::kernel.
Definition at line 49 of file splitchain.cpp.
References raft::map::exe(), and raft::kernel::input.
    {
        T a;
        input[ "0" ].pop(a);
        output[ "0" ].push(a - 10);
        return(raft::proceed);
    }
run() [11/12]
template<class T>
virtual raft::kstatus sub< T >::run () [inline], [virtual]
run - function to be extended for the actual execution. Code can be executed outside of the run function, i.e., with any function call, however the scheduler will only call the run function so it must initiate any follow-on behavior desired by the user.
Implements raft::kernel.
Definition at line 49 of file staticContJoinRetStruct.cpp.
References raft::map::exe(), and raft::kernel::input.
    {
        T a;
        input[ "0" ].pop(a);
        output[ "0" ].push(a - 10);
        return(raft::proceed);
    }
run() [12/12]
template<class T>
virtual raft::kstatus sub< T >::run () [inline], [virtual]
run - function to be extended for the actual execution. Code can be executed outside of the run function, i.e., with any function call, however the scheduler will only call the run function so it must initiate any follow-on behavior desired by the user.
Implements raft::kernel.
Definition at line 52 of file splitchainRetStruct.cpp.
References raft::map::exe(), and raft::kernel::input.
    {
        T a;
        input[ "0" ].pop(a);
        output[ "0" ].push(a - 10);
        return(raft::proceed);
    }
The documentation for this class was generated from the following files:
splitchain.cpp
splitchainRetStruct.cpp
staticContJoin.cpp
staticContJoinRetStruct.cpp
staticJoin.cpp
staticJoinRetStruct.cpp
staticLongSplitChain.cpp
staticLongSplitChainRetStruct.cpp
staticSplitChainJoin.cpp
staticSplitChainJoinRetStruct.cpp
staticSplitJoin.cpp
staticSplitJoinRetStruct.cpp