Sum< A, B, C > Class Template Reference
Public Member Functions
virtual raft::kstatus run ()
virtual raft::kstatus run ()
virtual raft::kstatus run ()
Additional Inherited Members
Detailed Description
template<typename A, typename B, typename C>
class Sum< A, B, C >
Definition at line 10 of file testsuite/allocate.cpp.
Member Function Documentation
run() [1/3]
template<typename A , typename B , typename C >
virtual raft::kstatus Sum< A, B, C >::run () [inline], [virtual]
run - function to be extended for the actual execution. Code can be executed outside of the run function, i.e., with any function call, however the scheduler will only call the run function so it must initiate any follow-on behavior desired by the user.
Implements raft::kernel.
Definition at line 20 of file testsuite/allocate.cpp.
References raft::map::exe(), and raft::kernel::input.
   {
      A a;
      B b;
      raft::signal sig_a(raft::none), sig_b(raft::none);
      input[ "input_a" ].pop(a, &sig_a);
      input[ "input_b" ].pop(b, &sig_b);
      assert(sig_a == sig_b);
      C c(a + b);
      output[ "sum" ].push(c , sig_a);
      if(sig_b == raft::eof)
      {
         return(raft::stop);
      }
      return(raft::proceed);
   }
run() [2/3]
template<typename A , typename B , typename C >
virtual raft::kstatus Sum< A, B, C >::run () [inline], [virtual]
run - function to be extended for the actual execution. Code can be executed outside of the run function, i.e., with any function call, however the scheduler will only call the run function so it must initiate any follow-on behavior desired by the user.
Implements raft::kernel.
Definition at line 22 of file portTypeException.cpp.
References raft::map::exe(), and raft::kernel::input.
   {
      A a;
      B b;
      raft::signal sig_a(raft::none), sig_b(raft::none);
      input[ "input_a" ].pop(a, &sig_a);
      input[ "input_b" ].pop(b, &sig_b);
      assert(sig_a == sig_b);
      C c(static_cast< C >(a + b));
      output[ "sum" ].push(c , sig_a);
      if(sig_b == raft::eof)
      {
         return(raft::stop);
      }
      return(raft::proceed);
   }
run() [3/3]
template<typename A , typename B , typename C >
virtual raft::kstatus Sum< A, B, C >::run () [inline], [virtual]
run - function to be extended for the actual execution. Code can be executed outside of the run function, i.e., with any function call, however the scheduler will only call the run function so it must initiate any follow-on behavior desired by the user.
Implements raft::kernel.
Definition at line 23 of file peek.cpp.
References raft::map::exe(), and raft::kernel::input.
   {
      output[ "sum" ].push(raft::sum< T >(input[ "input_a" ],
                                            input[ "input_b" ]));
      return(raft::proceed);
   }
The documentation for this class was generated from the following files:
testsuite/allocate.cpp
peek.cpp
portTypeException.cpp