common Class Reference
#include <common.hpp>
Static Public Member Functions
static std::string __printClassName (const std::string &&obj_name)
static std::string printClassNameFromStr (const std::string &&str)
template<class K >
static std::string printClassName (K &k)
Detailed Description
common.hpp - static helper functions of various types
Author
: Jonathan Beard
Version
: Sun May 10 19:10:06 2015
Copyright 2015 Jonathan Beard
Licensed under the Apache License, Version 2.0 (the `License`); you may not use this file except in compliance with the License. You may obtain a copy of the License at:
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an `AS IS` BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Definition at line 28 of file common.hpp.
Member Function Documentation
__printClassName()
std::string common::__printClassName (const std::string && obj_name) [static]
__printClassName - helper function for below function, basically see the more complete docs below for the delta, the string passed to this function should be the name of the class from either the typeinfo or typeid(xx).name() call. user must delete this, make string then delete
Definition at line 7 of file common.cpp.
Referenced by printClassName().
{
   /** user must delete this, make string then delete **/
   return(boost::core::demangle(obj_name.c_str()));
}
printClassName()
template<class K >
static std::string common::printClassName (K & k) [inline], [static]
pringClassName - takes in a class reference and prints the class name using cxx-demangle. I basically got tired of typing all the error checking code over and over so here's a simplified interface for it.
Parameters
k - Class reference for which you want the class.
Returns
std::string
Definition at line 51 of file common.hpp.
References __printClassName().
Referenced by GraphTools::BFS(), and MapBase::join().
{
   return(common::__printClassName(typeid(k).name()));
}
The documentation for this class was generated from the following files:
common.hpp
common.cpp