Schedule Class Reference
Public Member Functions
Schedule (raft::map &map)
virtual ~Schedule ()=default
virtual void start ()=0
virtual void init ()
virtual void scheduleKernel (raft::kernel *const kernel)
Static Public Member Functions
static bool kernelRun (raft::kernel *const kernel, volatile bool &finished, jmp_buf *gotostate=nullptr, jmp_buf *kernel_state=nullptr)
Protected Member Functions
virtual void handleSchedule (raft::kernel *const kernel)=0
Static Protected Member Functions
static raft::kstatus checkSystemSignal (raft::kernel *const kernel, void *data, SystemSignalHandler &handlers)
static raft::kstatus quitHandler (FIFO &fifo, raft::kernel *kernel, const raft::signal signal, void *data)
static void invalidateOutputPorts (raft::kernel *kernel)
static bool kernelHasInputData (raft::kernel *kernel)
static bool kernelHasNoInputPorts (raft::kernel *kernel)
static void setPtrSets (raft::kernel *const kernel, ptr_map_t *const in, ptr_set_t *const out, ptr_set_t *const peekset)
static void fifo_gc (ptr_map_t *const in, ptr_set_t *const out, ptr_set_t *const peekset)
Protected Attributes
SystemSignalHandler handlers
kernelkeeper & kernel_set
kernelkeeper & source_kernels
kernelkeeper & dst_kernels
Detailed Description
Definition at line 35 of file schedule.hpp.
Constructor & Destructor Documentation
Schedule()
Schedule::Schedule (raft::map & map)
Schedule - base constructor takes a map object so that all sub-classes can access some of the map features through the schedule sub-class accessors.
Parameters
map - Map&
Definition at line 10 of file schedule.cpp.
References SystemSignalHandler::addHandler(), handlers, and quitHandler().
                                 : kernel_set(map.all_kernels),
                                 source_kernels(map.source_kernels),
                                 dst_kernels(map.dst_kernels)
{
   //TODO, see if we want to keep this
   handlers.addHandler(raft::quit, Schedule::quitHandler);
}
 Schedule()
virtual Schedule::~Schedule () [virtual], [default]
destructor, takes care of cleanup
Member Function Documentation
checkSystemSignal()
raft::kstatus Schedule::checkSystemSignal (raft::kernel *const kernel, void * data, SystemSignalHandler & handlers) [static], [protected]
checkSystemSignal - check the incomming streams for the param kernel for any system signals, if there is one then consume the signal and perform the appropriate action.
Parameters
kernel - raft::kernel
data - void*, use this if any further info is needed in future implementations of handlers
Returns
raft::kstatus, proceed unless a stop signal is received
TODO, right now there is special behavior for term signal only, what should we do with others? Need to decide that.
Definition at line 58 of file schedule.cpp.
References SystemSignalHandler::callHandler(), and raft::kernel::input.
{
   auto &input_ports(kernel->input);
   raft::kstatus ret_signal(raft::proceed);
   for(auto &port : input_ports)
   {
      if(port.size() == 0)
      {
         continue;
      }
      const auto curr_signal(port.signal_peek());
      if(R_UNLIKELY(
         (curr_signal > 0 && curr_signal < raft::MAX_SYSTEM_SIGNAL)))
      {
         port.signal_pop();
         /**
          * TODO, right now there is special behavior for term signal only,
          * what should we do with others? Need to decide that.
          */
         if(handlers.callHandler(curr_signal,
                               port,
                               kernel,
                               data) == raft::stop)
         {
            ret_signal = raft::stop;
         }
      }
   }
   return(ret_signal);
}
init()
void Schedule::init () [virtual]
init - call to pre-process all kernels, this function is called by the map object befure calling start. default, do nothing
Definition at line 20 of file schedule.cpp.
{
   /** default, do nothing **/
}
kernelHasInputData()
bool Schedule::kernelHasInputData (raft::kernel * kernel) [static], [protected]
kernelHasInputData - check each input port for available data, returns true if any of the input ports has available data.
Parameters
kernel - raft::kernel
Returns
bool - true if input data available.
only output ports, keep calling till exits
Definition at line 120 of file schedule.cpp.
References raft::kernel::input.
Referenced by kernelRun().
{
   auto &port_list(kernel->input);
   if(! port_list.hasPorts())
   {
      /** only output ports, keep calling till exits **/
      return(true);
   }
   for(auto &port : port_list)
   {
      const auto size(port.size());
      if(size > 0)
      {
         return(true);
      }
   }
   return(false);
}
kernelHasNoInputPorts()
bool Schedule::kernelHasNoInputPorts (raft::kernel * kernel) [static], [protected]
kernelHasNoInputPorts - pretty much exactly like the function name says, if the param kernel has no valid input ports (this function assumes that kernelHasInputData() has been called and returns false before this function is called) then it returns true. kernel - raft::kernel*
Returns
bool - true if no valid input ports avail
assume data check is already complete
Definition at line 142 of file schedule.cpp.
References raft::kernel::input.
Referenced by kernelRun().
{
   auto &port_list(kernel->input);
   /** assume data check is already complete **/
   for(auto &port : port_list)
   {
      if(! port.is_invalid())
      {
         return(false);
      }
   }
   return(true);
}
kernelRun()
bool Schedule::kernelRun (raft::kernel *const kernel, volatile bool & finished, jmp_buf * gotostate = nullptr, jmp_buf * kernel_state = nullptr) [static]
kernelRun - all the logic necessary to run a single kernel successfully. Any additional signal handling should be handled by this function as its the only one that will be universally called by the scheduler.
Parameters
kernel - raft::kernel *const object, non-null kernel
finished - volatile bool - function sets to true when done.
Returns
true if run with no need for jmp_buf, false if the scheduler needs to run again with the kernel_state
must recheck data items again after port valid check, there could have been a push between these two conditional statements.
Definition at line 158 of file schedule.cpp.
References kernelHasInputData(), kernelHasNoInputPorts(), and raft::kernel::run().
Referenced by kernel_container::container_run(), and simple_schedule::simple_run().
{
   UNUSED(gotostate);
   UNUSED(kernel_state);
   if(kernelHasInputData(kernel))
   {
      const auto sig_status(kernel->run());
      if(sig_status == raft::stop)
      {
         invalidateOutputPorts(kernel);
         finished = true;
      }
   }
   /**
    * must recheck data items again after port valid check, there could
    * have been a push between these two conditional statements.
    */
   if(kernelHasNoInputPorts(kernel) && !
      kernelHasInputData(kernel))
   {
      invalidateOutputPorts(kernel);
      finished = true;
   }
   return(true);
}
quitHandler()
raft::kstatus Schedule::quitHandler (FIFO & fifo, raft::kernel * kernel, const raft::signal signal, void * data) [static], [protected]
quiteHandler - performs the actions needed when a port sends a quite signal (normal termination), this is most likely due to the end of data.
Parameters
fifo - FIFO& that sent the signal
kernel - raft::kernel*
signal - raft::signal
data - void*, vain attempt to future proof
NOTE: This should be the only action needed currently, however that may change in the futre with more features and systems added.
Definition at line 27 of file schedule.cpp.
References FIFO::invalidate().
Referenced by Schedule().
{
   /**
    * NOTE: This should be the only action needed
    * currently, however that may change in the futre
    * with more features and systems added.
    */
   UNUSED(kernel);
   UNUSED(signal);
   UNUSED(data);
   fifo.invalidate();
   return(raft::stop);
}
scheduleKernel()
void Schedule::scheduleKernel (raft::kernel *const kernel) [virtual]
scheduleKernel - adds the kernel `kernel` to the schedule, ensures that it is run. Other than that there are no guarantees for its execution. The base version should do for most, however feel free to re-implement in derived class as long as the source_kernels has all of the source kernels, dst_kernels has all of the destination kernels, and kernel_set has all of the kernels. Before you drop in a kernel, it better be ready to go..all allocations should be complete.
Parameters
kernel - raft::kernel*
NOTE: The kernel param should be ready to rock, we just need to add it here. The data structures xx_kernels all expect a fully ready kernel, well the threads monitoring the system do at least and this is one. What we need to do to kick off the execution is add it to the handleSchedule virtual function which is implemented by each scheduler.
Definition at line 93 of file schedule.cpp.
References Port::hasPorts(), raft::kernel::input, and kernel_set.
Referenced by basic_parallel::start().
{
   /**
    * NOTE: The kernel param should be ready to rock,
    * we just need to add it here. The data structures
    * xx_kernels all expect a fully ready kernel, well
    * the threads monitoring the system do at least and
    * this is one. What we need to do to kick off the
    * execution is add it to the handleSchedule virtual
    * function which is implemented by each scheduler.
    */
   assert(kernel != nullptr);
   if(! kernel->input.hasPorts())
   {
      source_kernels += kernel;
   }
   if(! kernel->output.hasPorts())
   {
      dst_kernels += kernel;
   }
   kernel_set += kernel;
   handleSchedule(kernel);
   return;
}
setPtrSets()
void Schedule::setPtrSets (raft::kernel *const kernel, ptr_map_t *const in, ptr_set_t *const out, ptr_set_t *const peekset) [static], [protected]
setPtrSets - add the tracking object from the sub-class to track input/output ptrs in flight by the kernel. The structure will be the same across all in and output FIFOs, since from within a `kernel` each fifo is accessed with sequential consistency we won't need any fancy locking structures. on each kernel firing, these structures should be checked to see if any allocated objects (the only ones to be put in these sets, need to be `garbage
collected`
Parameters
kernel - raft::kernel* the one we're registering
in - set_t*, the input set
out - set_t*, the output set
Returns
void
looks a bit odd initially, but the same peekset is set for each kernel's FIFO's within the view of the kernel they'll be accessed sequentially so no contention
Definition at line 187 of file schedule.cpp.
References raft::kernel::input.
Referenced by simple_schedule::simple_run().
{
    assert(in != nullptr);
    assert(out != nullptr);
    assert(peekset != nullptr);
    /**
     * looks a bit odd initially, but the same
     * peekset is set for each kernel's FIFO's
     * within the view of the kernel they'll be
     * accessed sequentially so no contention
     */
    for(auto &port : kernel->input)
    {
        port.setPtrMap(in);
        port.setInPeekSet(peekset);
    }
    for(auto &port : kernel->output)
    {
        port.setPtrSet(out);
        port.setOutPeekSet(peekset);
    }
    return;
}
start()
virtual void Schedule::start () [pure virtual]
start - called to start execution of all kernels. Implementation specific so it is purely virtual.
Implemented in pool_schedule, and simple_schedule.
Member Data Documentation
handlers
SystemSignalHandler Schedule::handlers [protected]
signal handlers
Definition at line 179 of file schedule.hpp.
Referenced by Schedule().
kernel_set
kernelkeeper& Schedule::kernel_set [protected]
kernel set
Definition at line 182 of file schedule.hpp.
Referenced by scheduleKernel(), and simple_schedule::start().
The documentation for this class was generated from the following files:
schedule.hpp
schedule.cpp