last Class Reference
Public Member Functions
virtual raft::kstatus run ()
virtual raft::kstatus run ()
virtual raft::kstatus run ()
virtual raft::kstatus run ()
virtual raft::kstatus run ()
virtual raft::kstatus run ()
Additional Inherited Members
Detailed Description
Definition at line 107 of file allocatePopExternal.cpp.
Member Function Documentation
run() [1/6]
virtual raft::kstatus last::run () [inline], [virtual]
run - function to be extended for the actual execution. Code can be executed outside of the run function, i.e., with any function call, however the scheduler will only call the run function so it must initiate any follow-on behavior desired by the user.
Implements raft::kernel.
Definition at line 67 of file allocatePopInternal.cpp.
References raft::map::exe(), and raft::kernel::input.
    {
        obj_t in;
        input[ "x" ].pop(in);
        if(in != counter++)
        {
            std::cerr << "failed exit\n";
            exit(EXIT_FAILURE);
        }
        return(raft::proceed);
    }
run() [2/6]
virtual raft::kstatus last::run () [inline], [virtual]
run - function to be extended for the actual execution. Code can be executed outside of the run function, i.e., with any function call, however the scheduler will only call the run function so it must initiate any follow-on behavior desired by the user.
Implements raft::kernel.
Definition at line 93 of file allocatePopInternalObject.cpp.
References raft::map::exe().
    {
        obj_t mem;
        input[ "x" ].pop(mem);
        using index_type = std::remove_const_t<decltype(mem.length)>;
        for(index_type i(0); i < mem.length; i++)
        {
            //will fail if we've messed something up
            if(static_cast<std::size_t>(mem.pad[ i ]) != counter)
            {
                std::cerr << "failed to send correct item, failed test, exiting!!\n";
                exit(EXIT_FAILURE);
            }
        }
        counter++;
        return(raft::proceed);
    }
run() [3/6]
virtual raft::kstatus last::run () [inline], [virtual]
run - function to be extended for the actual execution. Code can be executed outside of the run function, i.e., with any function call, however the scheduler will only call the run function so it must initiate any follow-on behavior desired by the user.
Implements raft::kernel.
Definition at line 110 of file allocatePopPush.cpp.
References raft::map::exe().
    {
        auto &mem(input[ "x" ].peek< obj_t >());
        using index_type = std::remove_const_t<decltype(mem.length)>;
        for(index_type i(0); i < mem.length; i++)
        {
            //will fail if we've messed something up
            assert(static_cast<std::size_t>(mem.pad[ i ]) == counter);
        }
        input[ "x" ].unpeek();
        input[ "x" ].recycle();
        counter++;
        return(raft::proceed);
    }
run() [4/6]
virtual raft::kstatus last::run () [inline], [virtual]
run - function to be extended for the actual execution. Code can be executed outside of the run function, i.e., with any function call, however the scheduler will only call the run function so it must initiate any follow-on behavior desired by the user.
Implements raft::kernel.
Definition at line 111 of file allocateSendPush.cpp.
References raft::map::exe().
    {
        auto &mem(input[ "x" ].peek< obj_t >());
        for(auto i(0); i < mem.length; i++)
        {
            //will fail if we've messed something up
            if(static_cast<std::size_t>(mem.pad[ i ]) != counter)
            {
                std::cerr << "test failed\n";
                exit(EXIT_FAILURE);
            }
        }
        input[ "x" ].unpeek();
        input[ "x" ].recycle();
        counter++;
        return(raft::proceed);
    }
run() [5/6]
virtual raft::kstatus last::run () [inline], [virtual]
run - function to be extended for the actual execution. Code can be executed outside of the run function, i.e., with any function call, however the scheduler will only call the run function so it must initiate any follow-on behavior desired by the user. Jan 2016 - otherwise end up with a signed/unsigned compare w/auto
Implements raft::kernel.
Definition at line 117 of file allocatePopExternal.cpp.
References raft::map::exe().
    {
        obj_t mem;
        input[ "x" ].pop(mem);
        C.emplace_back(reinterpret_cast< std::uintptr_t >(&mem));
        /** Jan 2016 - otherwise end up with a signed/unsigned compare w/auto **/
        using index_type = std::remove_const_t<decltype(mem.length)>;
        for(index_type i(0); i < mem.length; i++)
        {
            //will fail if we've messed something up
            if(static_cast<std::size_t>(mem.pad[ i ]) != counter)
            {
                std::cerr << "failed test\n";
                exit(EXIT_FAILURE);
            }
        }
        counter++;
        return(raft::proceed);
    }
run() [6/6]
virtual raft::kstatus last::run () [inline], [virtual]
run - function to be extended for the actual execution. Code can be executed outside of the run function, i.e., with any function call, however the scheduler will only call the run function so it must initiate any follow-on behavior desired by the user.
Implements raft::kernel.
Definition at line 121 of file allocateSendRandomPush.cpp.
References raft::map::exe().
    {
        auto &mem(input[ "x" ].peek< obj_t >());
        for(auto i(0); i < mem.length; i++)
        {
            //will fail if we've messed something up
            assert(static_cast<std::size_t>(mem.pad[ i ]) == counter);
        }
        input[ "x" ].unpeek();
        input[ "x" ].recycle();
        counter += 2;
        return(raft::proceed);
    }
The documentation for this class was generated from the following files:
allocatePopExternal.cpp
allocatePopInternal.cpp
allocatePopInternalObject.cpp
allocatePopPush.cpp
allocateSendPush.cpp
allocateSendRandomPush.cpp