Pointer Class Reference
#include <pointer.hpp>
Public Member Functions
Pointer (const std::size_t cap)
Pointer (const std::size_t cap, const wrap_t wrap_set)
Pointer (Pointer *const other, const std::size_t new_cap)
Static Public Member Functions
static std::size_t val (Pointer *const ptr)
static void inc (Pointer *const ptr)
static void incBy (Pointer *const ptr, const std::size_t in)
static std::size_t wrapIndicator (Pointer *const ptr)
Detailed Description
pointer.hpp -
Author
: Jonathan Beard
Version
: Thu May 15 09:58:51 2014
Copyright 2014 Jonathan Beard
Licensed under the Apache License, Version 2.0 (the `License`); you may not use this file except in compliance with the License. You may obtain a copy of the License at:
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an `AS IS` BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Definition at line 29 of file pointer.hpp.
Constructor & Destructor Documentation
Pointer() [1/2]
Pointer::Pointer (const std::size_t cap) [inline]
Pointer - used to synchronize read and write pointers for the ring buffer. This class encapsulates wrapping.
Definition at line 38 of file pointer.hpp.
References inc(), incBy(), val(), and wrapIndicator().
: max_cap(cap){};
Pointer() [2/2]
Pointer::Pointer (Pointer *const other, const std::size_t new_cap)
Pointer - used to snchronize read and write pointers for the ring buffer, this constructer is a copy constructor that copies an old Pointer object and sets a new max_capacity
Parameters
other,const Pointer&, the other pointer to be cpied
new_cap,the new max cap
Definition at line 33 of file pointer.cpp.
References val().
                                            : Pointer(new_cap)
{
   const auto val(Pointer::val(other));
   a = val;
   b = val;
}
Member Function Documentation
inc()
void Pointer::inc (Pointer *const ptr) [static]
inc - increments the pointer, takes care of wrapping the pointers as well so you don't run off the page
Returns
std::size_t, current value of pointer after increment
Definition at line 56 of file pointer.cpp.
Referenced by Pointer().
{
   ptr->a = (ptr->a + 1) % ptr->max_cap;
   ptr->b = (ptr->b + 1) % ptr->max_cap;
   if(ptr->b == 0)
   {
      ptr->wrap_a++;
      ptr->wrap_b++;
   }
}
incBy()
void Pointer::incBy (Pointer *const ptr, const std::size_t in) [static]
incBy - increments the current pointer poisition by 'in' increments. To be used for range insertion and removal
Parameters
ptr - Pointer * const
in - const std::size_t
Returns
void
Definition at line 68 of file pointer.cpp.
Referenced by Pointer().
{
   ptr->a = (ptr->a + in) % ptr->max_cap;
   ptr->b = (ptr->b + in) % ptr->max_cap;
   if(ptr->b < in)
   {
      ptr->wrap_a++;
      ptr->wrap_b++;
   }
}
val()
std::size_t Pointer::val (Pointer *const ptr) [static]
val - returns the current value of val.
Returns
std::size_t, current 'true' value of the pointer
Definition at line 42 of file pointer.cpp.
Referenced by Pointer().
{
   struct{
      std::uint64_t a;
      std::uint64_t b;
   }copy;
   do{
      copy.a = ptr->a;
      copy.b = ptr->b;
   }while(copy.a != copy.b);
   return(copy.b);
}
wrapIndicator()
std::size_t Pointer::wrapIndicator (Pointer *const ptr) [static]
wrapIndiciator - returns the current wrap position, the read should never be ahead of the write, and at best they should be equal. This is used when determining to return max_cap or zero for the current queue size.
Returns
std::size_t
Definition at line 81 of file pointer.cpp.
Referenced by Pointer().
{
   struct{
      std::uint64_t a;
      std::uint64_t b;
   }copy;
   do{
      copy.a = ptr->wrap_a;
      copy.b = ptr->wrap_b;
   }while(copy.a != copy.b);
   return(copy.b);
}
The documentation for this class was generated from the following files:
pointer.hpp
pointer.cpp