raft::map Class Reference
Public Member Functions
map ()
virtual ~map ()=default
template<class partition = partition_dummy, class scheduler = simple_schedule, class allocator = dynalloc, class parallelism_monitor = basic_parallel>
void exe ()
kernel_pair_t operator+= (kpair &p)
Protected Member Functions
void joink (kpair *const next)
void checkEdges (kernelkeeper &source_k)
void enableDuplication (kernelkeeper &source, kernelkeeper &all)
Friends
class ::basic_parallel
class ::Schedule
class ::Allocate
Additional Inherited Members
Detailed Description
Definition at line 46 of file map.hpp.
Constructor & Destructor Documentation
map()
raft::map::map ()
map - constructor, really doesn't do too much at the monent and doesn't really need to.
map.cpp -
Author
: Jonathan Beard
Version
: Fri Sep 12 10:28:33 2014
Copyright 2014 Jonathan Beard
Licensed under the Apache License, Version 2.0 (the `License`); you may not use this file except in compliance with the License. You may obtain a copy of the License at:
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an `AS IS` BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Definition at line 39 of file map.cpp.
             : MapBase()
{
}
 map()
virtual raft::map::~map () [virtual], [default]
default destructor
Member Function Documentation
checkEdges()
void raft::map::checkEdges (kernelkeeper & source_k) [protected]
checkEdges - runs a breadth first search through the graph to look for disconnected edges.
Parameters
source_k - std::set< raft::kernel* >
Exceptions
PortException - thrown if an unconnected edge is found.
NOTE: will throw an error that we're not catching here if there are unconnected edges...this is something that a user will have to fix. Otherwise will return with no errors.
Definition at line 45 of file map.cpp.
References GraphTools::BFS().
Referenced by exe().
{
   auto &container(source_k.acquire());
   /**
    * NOTE: will throw an error that we're not catching here
    * if there are unconnected edges...this is something that
    * a user will have to fix. Otherwise will return with no
    * errors.
    */
   GraphTools::BFS(container,
                    [](PortInfo & a,
                        PortInfo & b,
                        void * const data)
                    {
                       UNUSED(a);
                       UNUSED(b);
                       UNUSED(data);
                       return;
                    },
                    nullptr,
                    true);
   source_k.release();
   return;
}
enableDuplication()
void raft::map::enableDuplication (kernelkeeper & source, kernelkeeper & all) [protected]
enableDuplication - add split / join kernels where needed, for the moment we're going with a simple split/join topology, however that doesn't mean that more complex topologies might not be implemented in the future.
Parameters
source_k - std::set< raft::kernel* > with sources
void insert(raft::kernel &a, PortInfo &a_out, raft::kernel &b, PortInfo &b_in, raft::kernel &i, PortInfo &i_in, PortInfo &i_out); don't have to do this but it makes it far more apparent where it comes from
need to grab impl of Lengauer and Tarjan dominators, use for SESE
in the interim, restrict to kernels that are simple to duplicate
NOTE: there's a better linear SESE algorithm jcb17May16
case of inline kernel
front -> kernel_a goes to front -> split -> kernel_a
now we need the port info from the input port on back
kernel_a -> back goes to kernel_a -> join -> back
finally set the flag to the scheduler so that the parallel map manager can pick it up an use it.
parallalizable source, single output no inputs
parallelizable sink, single input, no outputs
flag as candidate if the connecting kernel only has one input port.
simply flag as a candidate
Definition at line 76 of file map.cpp.
References GraphTools::BFS(), Port::count(), raft::kernel::input, MapBase::join(), and PortInfo::split_func.
Referenced by exe().
{
    auto &source_k(source.acquire());
    auto &all_k (all.acquire());
    /** don't have to do this but it makes it far more apparent where it comes from **/
    void * const kernel_ptr(reinterpret_cast< void* >(&all_k));
    using kernel_ptr_t = std::remove_reference< decltype(all_k) >::type;
    /** need to grab impl of Lengauer and Tarjan dominators, use for SESE **/
    /** in the interim, restrict to kernels that are simple to duplicate **/
    /** NOTE: there's a better linear SESE algorithm jcb17May16 **/
    GraphTools::BFS(source_k,
                     [](PortInfo &a, PortInfo &b, void *data)
                     {
                        auto * const all_k(reinterpret_cast< kernel_ptr_t* >(data));
                        if(a.out_of_order && b.out_of_order)
                        {
                           /** case of inline kernel **/
                           if(b.my_kernel->input.count() == 1 &&
                               b.my_kernel->output.count() == 1 &&
                               a.my_kernel->dup_candidate)
                           {
                              auto *kernel_a(a.my_kernel);
                              assert(kernel_a->input.count() == 1);
                              auto &port_info_front(kernel_a->input.getPortInfo());
                              auto *front(port_info_front.other_kernel);
                              auto &front_port_info(front->output.getPortInfo());
                              /**
                               * front -> kernel_a goes to
                               * front -> split -> kernel_a
                               */
                              auto *split(
                                 static_cast< raft::kernel* >(
                                    port_info_front.split_func()));
                              all_k->insert(split);
                              MapBase::insert(front, front_port_info,
                                               kernel_a, port_info_front,
                                               split);
                              assert(kernel_a->output.count() == 1);
                              /**
                               * now we need the port info from the input
                               * port on back
                               **/
                              /**
                               * kernel_a -> back goes to
                               * kernel_a -> join -> back
                               */
                              auto *join(static_cast< raft::kernel* >(a.join_func()));
                              all_k->insert(join);
                              MapBase::insert(a.my_kernel, a,
                                               b.my_kernel, b,
                                               join);
                              /**
                               * finally set the flag to the scheduler
                               * so that the parallel map manager can
                               * pick it up an use it.
                               */
                              a.my_kernel->dup_enabled = true;
                           }
                           /** parallalizable source, single output no inputs**/
                           else if(a.my_kernel->input.count() == 0 &&
                                    a.my_kernel->output.count() == 1)
                           {
                              auto *join(static_cast< raft::kernel* >(a.join_func()));
                              all_k->insert(join);
                              MapBase::insert(a.my_kernel, a,
                                               b.my_kernel, b,
                                               join);
                              a.my_kernel->dup_enabled = true;
                           }
                           /** parallelizable sink, single input, no outputs **/
                           else if(b.my_kernel->input.count() == 1 &&
                                    b.my_kernel->output.count() == 0)
                           {
                              auto *split(
                                 static_cast< raft::kernel* >(b.split_func()));
                              all_k->insert(split);
                              MapBase::insert(a.my_kernel, a,
                                               b.my_kernel, b,
                                               split);
                              b.my_kernel->dup_enabled = true;
                           }
                           /**
                            * flag as candidate if the connecting
                            * kernel only has one input port.
                            */
                           else if(b.my_kernel->input.count() == 1)
                           {
                              /** simply flag as a candidate **/
                              b.my_kernel->dup_candidate = true;
                           }
                        }
                     },
                     kernel_ptr,
                     false);
   source.release();
   all.release();
}
exe()
template<class partition = partition_dummy, class scheduler = simple_schedule, class allocator = dynalloc, class parallelism_monitor = basic_parallel>
void raft::map::exe () [inline]
FIXME, the graph tools need to take more than function, we're wasting time by traversing the graph twice....will take awhile with big graphs. check types, ensure all are linked
adds in split/join kernels
launch allocator in a thread
launch scheduler in thread
launch parallelism monitor
ref to this
allocator
scheduler
exit parameter
join scheduler first
scheduler done, cleanup alloc
no more need to duplicate kernels
all fifo's deallocated when alloc goes out of scope
Definition at line 92 of file map.hpp.
References MapBase::all_kernels, checkEdges(), enableDuplication(), joink(), operator+=(), MapBase::source_kernels, and MapBase::sub_maps.
Referenced by sum< T >::run(), Generate< T >::run(), print< T >::run(), Sum< A, B, C >::run(), sub< T >::run(), display< T >::run(), and last::run().
   {
      {
         auto &container(all_kernels.acquire());
         for(auto * const submap : sub_maps)
         {
            auto &subcontainer(submap->all_kernels.acquire());
            container.insert(subcontainer.begin(),
                              subcontainer.end());
            submap->all_kernels.release();
         }
         all_kernels.release();
      }
      /** check types, ensure all are linked **/
      checkEdges(source_kernels);
      partition pt;
      pt.partition(all_kernels);
      
      /** adds in split/join kernels **/
      //enableDuplication(source_kernels, all_kernels);
      volatile bool exit_alloc(false);
      allocator alloc((*this), exit_alloc);
      /** launch allocator in a thread **/
      std::thread mem_thread([&](){
         alloc.run();
      });
     
      alloc.waitTillReady();
      scheduler sched((*this));
      sched.init();
      
      /** launch scheduler in thread **/
      std::thread sched_thread([&](){
         sched.start();
      });
      volatile bool exit_para(false);
      /** launch parallelism monitor **/
      parallelism_monitor pm((*this) /** ref to this **/,
                              alloc /** allocator **/,
                              sched /** scheduler **/,
                              exit_para /** exit parameter **/);
      std::thread parallel_mon([&](){
         pm.start();
      });
      /** join scheduler first **/
      sched_thread.join();
      /** scheduler done, cleanup alloc **/
      exit_alloc = true;
      mem_thread.join();
      /** no more need to duplicate kernels **/
      exit_para = true;
      parallel_mon.join();
      /** all fifo's deallocated when alloc goes out of scope **/
      return;
   }
joink()
void raft::map::joink (kpair *const next) [protected]
joink - convenience function for joining kernels from kpair objects
Parameters
next - kpair* const, kpair created from linking process
might be able to do better by re-doing with templates
single input, single output, hopefully
Definition at line 179 of file map.cpp.
References MapBase::link().
Referenced by exe(), and operator+=().
{
        /** might be able to do better by re-doing with templates **/
        if(next->has_src_name && next->has_dst_name)
        {
            if(next->out_of_order)
            {
                (this)->link< raft::order::out >(next->src,
                                                  next->src_name,
                                                  next->dst,
                                                  next->dst_name);
            }
            else
            {
                (this)->link(next->src,
                              next->src_name,
                              next->dst,
                              next->dst_name);
            }
        }
        else if(next->has_src_name && ! next->has_dst_name)
        {
            if(next->out_of_order)
            {
                (this)->link< raft::order::out >(next->src,
                                                  next->src_name,
                                                  next->dst);
            }
            else
            {
                (this)->link(next->src,
                              next->src_name,
                              next->dst);
            }
        }
        else if(! next->has_src_name && next->has_dst_name)
        {
            if(next->out_of_order)
            {
                (this)->link< raft::order::out >(next->src,
                                                  next->dst,
                                                  next->dst_name);
            }
            else
            {
                (this)->link(next->src,
                              next->dst,
                              next->dst_name);
            }
        }
        else /** single input, single output, hopefully **/
        {
            if(next->out_of_order)
            {
                (this)->link< raft::order::out >(next->src,
                                                  next->dst);
            }
            else
            {
                (this)->link(next->src,
                              next->dst);
            }
        }
}
operator+=()
kernel_pair_t raft::map::operator+= (kpair & p)
invoked to add kernel links to the map, returns an iterator to a list of the last kernels added to the map via the += start at the head, go forward
init return struct
set to true when we've done the first pass so that the ret_kernel_pair has the correct source kernels for this addition to the map most of the time this will look just like a '>>' op, but others this will get quite complicated
used to do nested splits
dup kernels arranged in `groups` so that a =< b a -> b1 a -> b2 and b^n is one group each kernel attached to b^n is then chained group to group until we reduce
keep # of out-edges for splits
could throw an exception so use push_back
start kernels vector off emplace used since kernel can't throw an exception
hold on to these for a bit so we can back track if needed
loop over chain
mult kernels going ot single kernel
whoops, looks like we need to clear the source ret_kernel_pair. also reset initialized so we capture all the new source kernels that are added.
unique ptr
don't need these anymore
now old dst (in temp_groups) become new sources
groups should now have the final destinations across multiple groups potentially. Take these, flatten to a single destination for the return vector since this is what the specification expects (i.e., all actual end destinations added to map....which are the last kernels added or leaf nodes).
unique ptr
TODO, need to get the kernel_pair_t to return the full list of kernels. Basically need to go back and pass the kernel_pair_t through the split/cont/join in order ot get the right kernels into the list, especially ones that are cloned internally otherwise the user might not get the returns that the expected.
Definition at line 248 of file map.cpp.
References kernel_pair_t::addDst(), kernel_pair_t::addSrc(), Port::begin(), kernel_pair_t::clearSrc(), raft::kernel::clone(), Port::count(), Port::end(), raft::kernel::input, MapBase::join(), and joink().
Referenced by exe().
{
    kpair * const pair(&p);
    assert(pair != nullptr);
    
    /** start at the head, go forward **/
    kpair *next = pair->head;
    assert(next != nullptr);
    
    /** init return struct **/
    kernel_pair_t ret_kernel_pair;
    
    /**
     * set to true when we've done the first pass
     * so that the ret_kernel_pair has the correct
     * source kernels for this addition to the map
     * most of the time this will look just like
     * a '>>' op, but others this will get quite
     * complicated
     */
    bool initialized(false);
    
    /** used to do nested splits **/
    enum sj_t : std::int8_t { split, join, cont };
    const static std::array< std::string, 3 > sj_t_str(
        {{ "split", "join", "cont" }}
    );
    auto next_link_type([](const kpair * const k) -> sj_t
    {
        if(k->split_to && ! k->join_from)
        {
            return(split);
        }
        else if(! k->split_to && k->join_from)
        {
            return(join);
        }
        else if(! k->split_to && ! k->join_from)
        {
            return(cont);
        }
        else
        {
            throw InvalidTopologyOperationException("Invalid ordering of topology operators \"<=\", \">>\"
      , \">=.\" Please check and try again\n");
        }
        //should never reach here **/
        assert(false);
        return(cont);
    });
    std::stack< sj_t > stack;
    /**
     * dup kernels arranged in "groups" so that
     * a =< b
     * a -> b1
     * a -> b2
     * and b^n is one group
     * each kernel attached to b^n is
     * then chained group to group
     * until we reduce
     */
    kernels_t groups;
    /**
     * keep # of out-edges for splits
     */
    split_stack_t split_out_edges;
    /** could throw an exception so use push_back **/
    groups.push_back(up_group_t(new group_t()));
    /**
     * start kernels vector off
     * emplace used since kernel can't throw an exception
     */
    groups.back()->emplace_back(next->src);
    /** hold on to these for a bit so we can back track if needed **/
    std::vector< kpair* > kpair_store;
    /** loop over chain **/
    while(next != nullptr)
    {
        stack.push(next_link_type(next));
        decltype(groups) temp_groups;
        switch(stack.top())
        {
            case(cont):
            {
                inline_cont(groups,
                             temp_groups,
                             next);
                //done, move on
                stack.pop();
            }
            break;
            case(split):
            {
                inline_split(split_out_edges,
                              groups,
                              temp_groups,
                              next);
            }
            break;
            case(join):
            {
                //make sure something bad didn't happen
                stack.pop();
                if(stack.size() == 0 /** mult kernels going ot single kernel **/)
                {
                    /**
                     * whoops, looks like we need to clear the source
                     * ret_kernel_pair. also reset initialized so we
                     * capture all the new source kernels that are added.
                     */
                    ret_kernel_pair.clearSrc();
                    initialized = false;
                    inline_dup_join(groups,
                                     temp_groups,
                                     next);
                }
                else if(stack.top() == split)
                {
                    //can pop now, don't need the old split
                    stack.pop();
                    inline_join(split_out_edges,
                                 groups,
                                 temp_groups,
                                 next);
                }
                else
                {
                    assert(false);
                }
            }
            break;
            default:
                assert(false);
        }
        if(! initialized)
        {
            for(/** unique ptr **/ auto &groups_ptr : groups)
            {
                for(auto * const kernel : (*groups_ptr))
                {
                    assert(kernel != nullptr);
                    ret_kernel_pair.addSrc(*kernel);
                }
            }
            initialized = true;
        }
        /** don't need these anymore **/
        groups.clear();
        /** now old dst (in temp_groups) become new sources **/
        groups = std::move(temp_groups);
        
        kpair * const temp_kpair = next;
        next = next->next;
        kpair_store.emplace_back(temp_kpair);
    }
    
    /**
     * groups should now have the final destinations across
     * multiple groups potentially. Take these, flatten to
     * a single destination for the return vector since this
     * is what the specification expects (i.e., all actual
     * end destinations added to map....which are the last
     * kernels added or leaf nodes).
     */
    for(/** unique ptr **/ auto &groups_ptr : groups)
    {
        for(auto * const kernel : (*groups_ptr))
        {
            assert(kernel != nullptr);
            ret_kernel_pair.addDst(*kernel);
        }
    }
    
    
    
    for(auto *ptr : kpair_store)
    {
        delete(ptr);
    }
    /**
     * TODO, need to get the kernel_pair_t to
     * return the full list of kernels. Basically
     * need to go back and pass the kernel_pair_t
     * through the split/cont/join in order ot
     * get the right kernels into the list, especially
     * ones that are cloned internally otherwise
     * the user might not get the returns that
     * the expected.
     */
    return(ret_kernel_pair);
}
Friends And Related Function Documentation
::basic_parallel
friend class ::basic_parallel [friend]
TODO, refactor basic_parallel base class to match the all caps base class coding style
Definition at line 191 of file map.hpp.
The documentation for this class was generated from the following files:
map.hpp
map.cpp