Allocate Class Reference
Public Member Functions
Allocate (raft::map &map, volatile bool &exit_alloc)
virtual ~Allocate ()
virtual void run ()=0
void waitTillReady ()
Protected Member Functions
void initialize (PortInfo *const src, PortInfo *const dst, FIFO *const fifo)
virtual void allocate (PortInfo &a, PortInfo &b, void *data)
void setReady ()
Protected Attributes
kernelkeeper & source_kernels
kernelkeeper & all_kernels
std::set< FIFO *> allocated_fifo
volatile bool & exit_alloc
Friends
class basic_parallel
Detailed Description
Definition at line 58 of file allocate.hpp.
Constructor & Destructor Documentation
Allocate()
Allocate::Allocate (raft::map & map, volatile bool & exit_alloc)
Allocate - base constructor, really doesn't do too much save for setting the global variables all_kernels and source_kernels from the Map object.
Parameters
map - raft::map&
exit_alloc - bool used to terminate loop, for monitoring allocations, controlled by map object.
allocate.cpp -
Author
: Jonathan Beard
Version
: Tue Sep 16 20:20:06 2014
Copyright 2014 Jonathan Beard
Licensed under the Apache License, Version 2.0 (the `License`); you may not use this file except in compliance with the License. You may obtain a copy of the License at:
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an `AS IS` BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Definition at line 30 of file src/allocate.cpp.
                                                            :
   source_kernels(map.source_kernels),
   all_kernels(map.all_kernels),
   exit_alloc(exit_alloc)
{
}
 Allocate()
Allocate::~Allocate () [virtual]
destructor
Definition at line 37 of file src/allocate.cpp.
References allocated_fifo.
{
   for(FIFO *f : allocated_fifo)
   {
      delete(f);
   }
}
Member Function Documentation
initialize()
void Allocate::initialize (PortInfo *const src, PortInfo *const dst, FIFO *const fifo) [protected]
initialize - internal method to be used within the run method takes care of the initialization using the already allocated FIFO object passed as a param. This function will throw an exception if either port (src or dst) have already been allocated.
Parameters
src - PortInfo*, nullptr if not to be set
dst - PortInfo*, nullptr if not to be set
fifo - FIFO*
Exceptions
PortDoubleInitializeException - if either port is already initialized.
NOTE: this list simply speeds up the monitoring if we want it
Definition at line 58 of file src/allocate.cpp.
References allocated_fifo, PortInfo::const_map, PortInfo::getFIFO(), FIFO::set_dst_kernel(), FIFO::set_src_kernel(), and PortInfo::setFIFO().
Referenced by stdalloc::run().
{
   assert(fifo != nullptr);
   assert(dst != nullptr);
   assert(src != nullptr);
   if(src->getFIFO() != nullptr)
   {
      throw PortDoubleInitializeException(
         "Source port \"" + src->my_name + "\" already initialized!");
   }
   if(dst->getFIFO() != nullptr)
   {
      throw PortDoubleInitializeException(
         "Destination port \"" + dst->my_name + "\" already initialized!");
   }
   src->setFIFO(fifo);
   fifo->set_src_kernel(src->my_kernel);
   dst->setFIFO(fifo);
   fifo->set_dst_kernel(dst->my_kernel);
   /** NOTE: this list simply speeds up the monitoring if we want it **/
   allocated_fifo.insert(fifo);
}
run()
virtual void Allocate::run () [pure virtual]
run - implement this function to create a new allocator, will be run inside a thread so exits when done but if run-time monitoring is desired then this is the place to do it.
Implemented in stdalloc, and dynalloc.
setReady()
void Allocate::setReady () [protected]
setReady - call within the implemented run function to signal that the initial allocations have been completed.
Definition at line 52 of file src/allocate.cpp.
Referenced by dynalloc::run(), and stdalloc::run().
{
   ready = true;
}
waitTillReady()
void Allocate::waitTillReady ()
waitTillReady - call after initializing the allocate thread, returns when the initial allocation is complete.
Definition at line 46 of file src/allocate.cpp.
{
   while(! ready);
}
Member Data Documentation
allocated_fifo
std::set< FIFO* > Allocate::allocated_fifo [protected]
keeps a list of all currently allocated FIFO objects, set from within the initialize function.
Definition at line 124 of file allocate.hpp.
Referenced by initialize(), and ~Allocate().
exit_alloc
volatile bool& Allocate::exit_alloc [protected]
exit_alloc - bool whose value is set by the map object, controls when the loop within the alloc thread is exited.
Definition at line 131 of file allocate.hpp.
Referenced by dynalloc::run().
source_kernels
kernelkeeper& Allocate::source_kernels [protected]
both convenience structs, hold exactly what the names say
Definition at line 117 of file allocate.hpp.
Referenced by dynalloc::run(), and stdalloc::run().
The documentation for this class was generated from the following files:
allocate.hpp
src/allocate.cpp