stdalloc Class Reference
Public Member Functions
stdalloc (raft::map &map, volatile bool &exit_alloc)
virtual ~stdalloc ()
virtual void run ()
Additional Inherited Members
Detailed Description
Definition at line 31 of file stdalloc.hpp.
Constructor & Destructor Documentation
stdalloc()
stdalloc::stdalloc (raft::map & map, volatile bool & exit_alloc)
stdalloc - default constructor, calls base allocate constructor of Allcoate which sets the map object. After setting this object loose in a thread, the notReady() function must be called so that the queue sees fully allocated buffers as opposed ot null objects.
Parameters
map - Map&, map with full application
exit_alloc - bool whose value is set by the map object owning this one. Controls when the loop within the run thread is exited.
stdalloc.cpp - simple allocation, just initializes the FIFO with a fixed size buffer (512 items) with an alignment of 16-bytes. This can easily be changed by changing the constants below.
Author
: Jonathan Beard
Version
: Sat Sep 20 19:56:49 2014
Copyright 2014 Jonathan Beard
Licensed under the Apache License, Version 2.0 (the `License`); you may not use this file except in compliance with the License. You may obtain a copy of the License at:
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an `AS IS` BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Definition at line 31 of file stdalloc.cpp.
                                               : Allocate(map,
      exit_alloc)
{
}
 stdalloc()
stdalloc::~stdalloc () [virtual]
destructor, doesn't really do much at he moment.
Definition at line 36 of file stdalloc.cpp.
{
}
Member Function Documentation
run()
void stdalloc::run () [virtual]
run - call within a thread, internally we could have a loop before exiting but this version simply allocates and exits. assume everyone needs a heap for the moment to get working
check and see if a has a defined allocation
check for pre-existing alloc size for test purposes
size
align
Implements Allocate.
Definition at line 41 of file stdalloc.cpp.
References GraphTools::BFS(), PortInfo::const_map, Allocate::initialize(), Allocate::setReady(), Allocate::source_kernels, and PortInfo::type.
{
   auto alloc_func = [&](PortInfo &a,
                          PortInfo &b,
                          void *data)
   {
      (void) data;
      assert(a.type == b.type);
      /** assume everyone needs a heap for the moment to get working **/
      instr_map_t *func_map(a.const_map[ Type::Heap ]);
      FIFO *fifo(nullptr);
      auto test_func((*func_map)[ false ]);
      /** check and see if a has a defined allocation **/
      if(a.existing_buffer != nullptr)
      {
         fifo = test_func(a.nitems,
                           a.start_index,
                           a.existing_buffer);
      }
      else
      {
         /** check for pre-existing alloc size for test purposes **/
         fifo = test_func(a.fixed_buffer_size != 0 ?
                              a.fixed_buffer_size : 4 /** size **/,
                           16 /** align **/,
                           nullptr /* data struct **/);
      }
      assert(fifo != nullptr);
      (this)->initialize(&a, &b, fifo);
   };
   auto &container((this)->source_kernels.acquire());
   GraphTools::BFS(container, alloc_func);
   (this)->source_kernels.release();
   (this)->setReady();
   return;
}
The documentation for this class was generated from the following files:
stdalloc.hpp
stdalloc.cpp