simple_schedule Class Reference
Classes
struct thread_data
struct thread_info_t
Public Member Functions
simple_schedule (raft::map &map)
virtual void start ()
Protected Member Functions
void handleSchedule (raft::kernel *const kernel)
Static Protected Member Functions
static void simple_run (void *data)
Protected Attributes
std::mutex thread_map_mutex
std::vector< thread_info_t *> thread_map
Additional Inherited Members
Detailed Description
Definition at line 32 of file simpleschedule.hpp.
Constructor & Destructor Documentation
simple_schedule()
simple_schedule::simple_schedule (raft::map & map)
simpleschedule.cpp -
Author
: Jonathan Beard
Version
: Thu Sep 11 15:49:57 2014
Copyright 2014 Jonathan Beard
Licensed under the Apache License, Version 2.0 (the `License`); you may not use this file except in compliance with the License. You may obtain a copy of the License at:
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an `AS IS` BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Definition at line 47 of file simpleschedule.cpp.
                                               : Schedule(map)
{
}
Member Function Documentation
handleSchedule()
void simple_schedule::handleSchedule (raft::kernel *const kernel) [protected], [virtual]
TODO: lets add the affinity dynamically here
thread function takes a reference back to the scheduler accessible done boolean flag, essentially when the kernel is done, it can be rescheduled...and this handles that.
we got here, unlock
Implements Schedule.
Definition at line 122 of file simpleschedule.cpp.
{
      /**
       * TODO: lets add the affinity dynamically here
       */
      auto * const th_info(new thread_info_t(kernel));
      /**
       * thread function takes a reference back to the scheduler
       * accessible done boolean flag, essentially when the
       * kernel is done, it can be rescheduled...and this
       * handles that.
       */
      while(! thread_map_mutex.try_lock())
      {
         std::this_thread::yield();
      }
      thread_map.emplace_back(th_info);
      /** we got here, unlock **/
      thread_map_mutex.unlock();
      return;
}
simple_run()
void simple_schedule::simple_run (void * data) [static], [protected]
call does nothing if not available
Definition at line 145 of file simpleschedule.cpp.
References Schedule::kernelRun(), affinity::set(), and Schedule::setPtrSets().
{
   assert(data != nullptr);
   auto * const thread_d(reinterpret_cast< thread_data* >(data));
   ptr_map_t in;
   ptr_set_t out;
   ptr_set_t peekset;
   Schedule::setPtrSets(thread_d->k,
                        &in,
                        &out,
                        &peekset);
   if(thread_d->loc != -1)
   {
      /** call does nothing if not available **/
      affinity::set(thread_d->loc);
   }
   else
   {
#ifdef USE_PARTITION
       assert(false);
#endif
   }
   while(! *(thread_d->finished))
   {
      Schedule::kernelRun(thread_d->k, *(thread_d->finished));
      //takes care of peekset clearing too
      Schedule::fifo_gc(&in, &out, &peekset);
   }
}
start()
void simple_schedule::start () [virtual]
start - called to start execution of all kernels. Implementation specific so it is purely virtual. NOTE: this section is the same as the code in the `handleSchedule` function so that it doesn't call the lock for the thread map.
FIXME: the list could get huge for long running apps, need to delete these entries...especially since we have a lock on the list now
NOTE: added to keep from having to unlock these so frequently might need to make the interval adjustable dep. on app
Implements Schedule.
Definition at line 64 of file simpleschedule.cpp.
References Schedule::kernel_set.
{
   /**
    * NOTE: this section is the same as the code in the "handleSchedule"
    * function so that it doesn't call the lock for the thread map.
    */
   auto &container(kernel_set.acquire());
   for(auto * const k : container)
   {
      auto * const th_info(new thread_info_t(k));
      th_info->data.loc = k->getCoreAssignment();
      thread_map.emplace_back(th_info);
   }
   kernel_set.release();
   
   bool keep_going(true);
   while(keep_going)
   {
      while(! thread_map_mutex.try_lock())
      {
         std::this_thread::yield();
      }
      //exit, we have a lock
      keep_going = false;
      for(auto *t_info : thread_map)
      {
         if(! t_info->term)
         {
            //loop over each thread and check if done
            if(t_info->finished)
            {
               /**
                * FIXME: the list could get huge for long running apps,
                * need to delete these entries...especially since we have
                * a lock on the list now
                */
               t_info->th.join();
               t_info->term = true;
            }
            else /* a kernel ! finished */
            {
               keep_going = true;
            }
         }
      }
      //if we're here we have a lock and need to unlock
      thread_map_mutex.unlock();
      /**
       * NOTE: added to keep from having to unlock these so frequently
       * might need to make the interval adjustable dep. on app
       */
      std::chrono::milliseconds dura(3);
      std::this_thread::sleep_for(dura);
   }
   return;
}
The documentation for this class was generated from the following files:
simpleschedule.hpp
simpleschedule.cpp