SystemSignalHandler Class Reference
Public Member Functions
void addHandler (const raft::signal signal, sighandler handler)
raft::kstatus callHandler (const raft::signal signal, FIFO &fifo, raft::kernel *kernel, void *data)
Detailed Description
Definition at line 46 of file systemsignalhandler.hpp.
Member Function Documentation
addHandler()
void SystemSignalHandler::addHandler (const raft::signal signal, sighandler handler)
addHandler - adds the signal handler 'handler' to this container. If the handler already exists for that signal then the last one to get added supercedes it (i.e., we're relying on the base class to be called first and derived classes to potentially add newer handlers).
Parameters
signal - const raft::signal
handler - sighandler
Definition at line 37 of file systemsignalhandler.cpp.
Referenced by Schedule::Schedule().
{
   handlers[ signal ] = handler;
}
callHandler()
raft::kstatus SystemSignalHandler::callHandler (const raft::signal signal, FIFO & fifo, raft::kernel * kernel, void * data)
callHandler - calls the handler for the param signal, an exception is thrown if the signal doesn't have a handler and a sigterm is passed throughout the system.
Parameters
signal - const raft::signal
fifo - FIFO& current port that called the signal
kernel - raft::kernel*, currently called kernel
data - void*
Returns
raft::kstatus - returns whatever the handler says otherwise proceed
Exceptions
NoSignalHandlerFoundException
Definition at line 44 of file systemsignalhandler.cpp.
References NoSignalHandlerFoundException::NoSignalHandlerFoundException().
Referenced by Schedule::checkSystemSignal().
{
   auto ret_func(handlers.find(signal));
   if(ret_func == handlers.end())
   {
      throw NoSignalHandlerFoundException("No handler found for: " +
                                             std::to_string(signal));
   }
   else
   {
      return(
      (*ret_func).second(fifo,
                          kernel,
                          signal,
                          data));
   }
}
The documentation for this class was generated from the following files:
systemsignalhandler.hpp
systemsignalhandler.cpp